#!/bin/bash
# Apply the production Hermes lite/full runtime split.
# Idempotent: safe to re-run after git pull, profile install, or service restart.
# No secrets are written or printed. XHS account-backed cookies/tokens are
# intentionally removed because Xiaohongshu reading is public-only.

set -euo pipefail

REPO_ROOT="${RAN_AGENT_REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
HERMES_BIN="${HERMES_BIN:-hermes}"
FULL_HOME="${HERMES_HOME:-/home/ubuntu/.hermes-ran-agent}"
LITE_HOME="${HERMES_LITE_HOME:-$FULL_HOME/lite}"
RUNTIME_USER="${RAN_AGENT_RUNTIME_USER:-ubuntu}"
RUNTIME_GROUP="${RAN_AGENT_RUNTIME_GROUP:-$RUNTIME_USER}"
NODE_ENV_FILE="${RAN_AGENT_NODE_ENV_FILE:-/opt/ran_agent/.env.local}"
NODE_BRIDGE_ENV_FILE="${RAN_AGENT_NODE_BRIDGE_ENV_FILE:-/opt/ran_agent/node_bridge/.env.local}"
HERMES_GLOBAL_ENV_FILE="${HERMES_GLOBAL_ENV_FILE:-/home/ubuntu/.hermes/.env}"
SYSTEMD_DIR="${SYSTEMD_DIR:-/etc/systemd/system}"
RUNTIME_STATE_DIR="${RAN_AGENT_DEPLOY_STATE_DIR:-/opt/ran_agent/.ran_agent_state}"
RUNTIME_DEBUG_DIR="${RAN_AGENT_DEPLOY_DEBUG_DIR:-/opt/ran_agent/debug}"
LITE_SERVICE="$SYSTEMD_DIR/ran-agent-hermes.service"
FULL_SERVICE="$SYSTEMD_DIR/ran-agent-hermes-full.service"
OMBRE_SERVICE="$SYSTEMD_DIR/ran-agent-ombre-brain.service"
XHS_BROWSE_SERVICE="$SYSTEMD_DIR/ran-agent-xhs-browse.service"
XHS_PUBLIC_SIDECAR_SERVICE="$SYSTEMD_DIR/ran-agent-xhs-public-sidecar.service"
LITE_DROPIN_DIR="$SYSTEMD_DIR/ran-agent-hermes.service.d"
STALE_LITE_DROPINS=(
  "$LITE_DROPIN_DIR/30-hermes-env.conf"
  "$LITE_DROPIN_DIR/30-hermes-runtime.conf"
  "$LITE_DROPIN_DIR/90-lite-runtime.conf"
)
API_HOST="${API_SERVER_HOST:-127.0.0.1}"
LITE_PORT="${HERMES_LITE_API_PORT:-8642}"
FULL_PORT="${HERMES_FULL_API_PORT:-8643}"
LITE_PROFILE="ran-assistant-lite"
FULL_PROFILE="ran-assistant"
MODEL_NAME="deepseek-v4-flash"
BACKUP_DIR="$(mktemp -d)"
XHS_GENERIC_FALLBACK_PREPARE_TIMEOUT_SECONDS="${XHS_GENERIC_FALLBACK_PREPARE_TIMEOUT_SECONDS:-120}"
XHS_PUBLIC_SIDECAR_PREPARE_TIMEOUT_SECONDS="${XHS_PUBLIC_SIDECAR_PREPARE_TIMEOUT_SECONDS:-900}"
XHS_PUBLIC_SIDECAR_AUTO_PREPARE="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_AUTO_PREPARE:-true}"
XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_ENABLED:-true}"
XHS_PUBLIC_SIDECAR_HOST_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_HOST:-127.0.0.1}"
XHS_PUBLIC_SIDECAR_PORT_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_PORT:-18061}"
XHS_PUBLIC_SIDECAR_URL_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_URL:-http://$XHS_PUBLIC_SIDECAR_HOST_DEFAULT:$XHS_PUBLIC_SIDECAR_PORT_DEFAULT/xhs/detail}"
XHS_PUBLIC_SIDECAR_TIMEOUT_MS_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_TIMEOUT_MS:-90000}"
XHS_PUBLIC_HTML_FALLBACK_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_HTML_FALLBACK_ENABLED:-true}"
XHS_PUBLIC_SIDECAR_MARKER_PATH_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_MARKER_PATH:-/opt/ran_agent/.ran_agent_state/social_reader/xhs-public-sidecar-ready.json}"
XHS_PUBLIC_SIDECAR_ROOT_DIR_DEFAULT="${RAN_AGENT_DEPLOY_XHS_PUBLIC_SIDECAR_ROOT_DIR:-/opt/ran_agent/.ran_agent_state/xhs-public-sidecar}"
HERMES_CONTEXT_INJECTION_MODE_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CONTEXT_INJECTION_MODE:-auto}"
HERMES_CONTEXT_CACHE_STRATEGY_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CONTEXT_CACHE_STRATEGY:-balanced}"
HERMES_RECENT_TEXT_TURNS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_RECENT_TEXT_TURNS:-4}"
HERMES_RECENT_TEXT_CHAR_BUDGET_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_RECENT_TEXT_CHAR_BUDGET:-2400}"
HERMES_GLOBAL_RECENT_TURNS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_GLOBAL_RECENT_TURNS:-2}"
HERMES_GLOBAL_RECENT_CHAR_BUDGET_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_GLOBAL_RECENT_CHAR_BUDGET:-800}"
HERMES_ACTIVE_TOPIC_CHAR_BUDGET_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ACTIVE_TOPIC_CHAR_BUDGET:-400}"
HERMES_CONTINUITY_FRESHNESS_HOURS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CONTINUITY_FRESHNESS_HOURS:-24}"
HERMES_CACHE_FRIENDLY_HISTORY_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CACHE_FRIENDLY_HISTORY:-false}"
HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS:-6}"
HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET:-12000}"
HERMES_CACHE_FRIENDLY_HISTORY_PROFILE_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CACHE_FRIENDLY_HISTORY_PROFILE:-lite}"
HERMES_CACHE_TELEMETRY_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_CACHE_TELEMETRY_ENABLED:-true}"
HERMES_LITE_SOFT_RESET_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_LITE_SOFT_RESET_ENABLED:-true}"
HERMES_LITE_SOFT_RESET_DRY_RUN_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_LITE_SOFT_RESET_DRY_RUN:-false}"
HERMES_LITE_SOFT_RESET_MAX_DIGEST_CHARS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_LITE_SOFT_RESET_MAX_DIGEST_CHARS:-1200}"
HERMES_LITE_SOFT_RESET_KEEP_LAST_N_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_LITE_SOFT_RESET_KEEP_LAST_N:-4}"
HERMES_LITE_SOFT_RESET_STATE_FILE_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_LITE_SOFT_RESET_STATE_FILE:-.ran_agent_state/hermes/session_maintenance.json}"
HERMES_LITE_SOFT_RESET_DIGEST_DIR_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_LITE_SOFT_RESET_DIGEST_DIR:-.ran_agent_state/hermes/digests/}"
HERMES_ACTION_GATE_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ACTION_GATE_ENABLED:-true}"
HERMES_ACTION_GATE_MODE_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ACTION_GATE_MODE:-repair}"
HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS:-1}"
HERMES_ACTION_PENDING_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ACTION_PENDING_ENABLED:-true}"
HERMES_ACTION_PENDING_TTL_MINUTES_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ACTION_PENDING_TTL_MINUTES:-30}"
HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_REPLY_TIMEOUT_SECONDS:-1200}"
NODE_BRIDGE_QUICK_ACK_ENABLED_DEFAULT=false
NODE_BRIDGE_QUICK_ACK_TIMEOUT_MS_DEFAULT="${RAN_AGENT_DEPLOY_NODE_BRIDGE_QUICK_ACK_TIMEOUT_MS:-4500}"
NODE_BRIDGE_QUICK_ACK_TEXT_DEFAULT="${RAN_AGENT_DEPLOY_NODE_BRIDGE_QUICK_ACK_TEXT:-收到，正在处理。}"
FEISHU_SEND_TIMEOUT_SECONDS_DEFAULT="${RAN_AGENT_DEPLOY_FEISHU_SEND_TIMEOUT_SECONDS:-30}"
FEISHU_DOWNLOAD_TIMEOUT_SECONDS_DEFAULT="${RAN_AGENT_DEPLOY_FEISHU_DOWNLOAD_TIMEOUT_SECONDS:-30}"
HERMES_ENVIRONMENT_CONTEXT_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ENVIRONMENT_CONTEXT_ENABLED:-true}"
HERMES_ENVIRONMENT_WEATHER_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ENVIRONMENT_WEATHER_ENABLED:-true}"
HERMES_ENVIRONMENT_MAX_AGE_MS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ENVIRONMENT_MAX_AGE_MS:-1800000}"
HERMES_ENVIRONMENT_WEATHER_CACHE_MS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ENVIRONMENT_WEATHER_CACHE_MS:-600000}"
HERMES_ENVIRONMENT_TIMEZONE_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_ENVIRONMENT_TIMEZONE:-Asia/Shanghai}"
WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT="${RAN_AGENT_DEPLOY_WEIXIN_SDK_INBOUND_MEDIA_DIRS:-/tmp/weixin-agent/media/inbound}"
EXTERNAL_MCP_GATEWAY_ALLOW_ENV_ENABLE_DEFAULT="${RAN_AGENT_DEPLOY_EXTERNAL_MCP_GATEWAY_ALLOW_ENV_ENABLE:-true}"
EXTERNAL_MCP_GATEWAY_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_EXTERNAL_MCP_GATEWAY_ENABLED:-true}"
EXTERNAL_MCP_SYSTEM_QUEUE_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_EXTERNAL_MCP_SYSTEM_QUEUE_ENABLED:-true}"
EXTERNAL_MCP_ACTIVITY_RUNNER_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_EXTERNAL_MCP_ACTIVITY_RUNNER_ENABLED:-true}"
EXTERNAL_MCP_ACTIVITY_TICK_MS_DEFAULT="${RAN_AGENT_DEPLOY_EXTERNAL_MCP_ACTIVITY_TICK_MS:-60000}"
HERMES_PROACTIVE_EVENTS_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_PROACTIVE_EVENTS_ENABLED:-true}"
HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED:-true}"
HERMES_PROACTIVE_REMINDERS_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_PROACTIVE_REMINDERS_ENABLED:-true}"
HERMES_PROACTIVE_NOTIFY_MAX_CHARS_DEFAULT="${RAN_AGENT_DEPLOY_HERMES_PROACTIVE_NOTIFY_MAX_CHARS:-1600}"
PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS:-6,12,18,23}"
PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE:-0}"
PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED:-true}"
PERSONAL_AGENT_DAILY_CARRYOVER_HOUR_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_DAILY_CARRYOVER_HOUR:-4}"
PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE:-0}"
AI_DAILY_DIGEST_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_AI_DAILY_DIGEST_ENABLED:-true}"
AI_DAILY_DIGEST_HOUR_DEFAULT="${RAN_AGENT_DEPLOY_AI_DAILY_DIGEST_HOUR:-8}"
AI_DAILY_DIGEST_MINUTE_DEFAULT="${RAN_AGENT_DEPLOY_AI_DAILY_DIGEST_MINUTE:-0}"
PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS:-300}"
PERSONAL_AGENT_OCR_PROVIDER_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OCR_PROVIDER:-dashscope-qwen-vl-ocr}"
PERSONAL_AGENT_OCR_MODEL_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OCR_MODEL:-qwen-vl-ocr-2025-11-20}"
PERSONAL_AGENT_OCR_TIMEOUT_MS_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OCR_TIMEOUT_MS:-120000}"
OMBRE_BRAIN_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_ENABLED:-true}"
OMBRE_BRAIN_MCP_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_MCP_ENABLED:-true}"
OMBRE_BRAIN_RUNNER_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_RUNNER:-source}"
OMBRE_BRAIN_REPO_URL_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_REPO_URL:-https://github.com/P0luz/Ombre-Brain}"
OMBRE_BRAIN_HOME_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_HOME:-/opt/ran_agent/.ran_agent_state/ombre-brain}"
OMBRE_BRAIN_SOURCE_DIR_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_SOURCE_DIR:-$OMBRE_BRAIN_HOME_DEFAULT/upstream}"
OMBRE_BRAIN_VENV_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_VENV:-$OMBRE_BRAIN_HOME_DEFAULT/.venv}"
OMBRE_BUCKETS_DIR_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BUCKETS_DIR:-/opt/ran_agent/vault/ombre}"
OMBRE_BRAIN_IMAGE_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_IMAGE:-p0luz/ombre-brain:latest}"
OMBRE_BRAIN_BIND_HOST_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_BIND_HOST:-127.0.0.1}"
OMBRE_BRAIN_PORT_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_PORT:-18001}"
OMBRE_BRAIN_COMPOSE_FILE_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_COMPOSE_FILE:-$OMBRE_BRAIN_HOME_DEFAULT/docker-compose.yml}"
OMBRE_BRAIN_CONFIG_FILE_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_CONFIG_FILE:-$OMBRE_BRAIN_HOME_DEFAULT/config.yaml}"
OMBRE_BRAIN_STATUS_FILE_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_STATUS_FILE:-$OMBRE_BRAIN_HOME_DEFAULT/status.json}"
OMBRE_BRAIN_MCP_URL_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_MCP_URL:-http://$OMBRE_BRAIN_BIND_HOST_DEFAULT:$OMBRE_BRAIN_PORT_DEFAULT/mcp}"
OMBRE_BRAIN_MCP_EXTRA_URL_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_MCP_EXTRA_URL:-http://$OMBRE_BRAIN_BIND_HOST_DEFAULT:$OMBRE_BRAIN_PORT_DEFAULT/mcp-extra}"
OMBRE_BRAIN_HEALTH_URL_DEFAULT="${RAN_AGENT_DEPLOY_OMBRE_BRAIN_HEALTH_URL:-http://$OMBRE_BRAIN_BIND_HOST_DEFAULT:$OMBRE_BRAIN_PORT_DEFAULT/health}"
PERSONAL_AGENT_OMBRE_READ_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_READ_ENABLED:-true}"
PERSONAL_AGENT_OMBRE_WRITE_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_WRITE_ENABLED:-false}"
PERSONAL_AGENT_OMBRE_TIMEOUT_MS_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_TIMEOUT_MS:-1500}"
PERSONAL_AGENT_OMBRE_MAX_RESULTS_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_MAX_RESULTS:-3}"
PERSONAL_AGENT_OMBRE_MAX_CHARS_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_MAX_CHARS:-900}"
PERSONAL_AGENT_OMBRE_ANCHOR_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_ANCHOR_ENABLED:-true}"
PERSONAL_AGENT_OMBRE_I_ENABLED_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_I_ENABLED:-true}"
PERSONAL_AGENT_OMBRE_WRITE_MODE_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_WRITE_MODE:-guarded}"
PERSONAL_AGENT_OMBRE_BACKEND_DEFAULT="${RAN_AGENT_DEPLOY_PERSONAL_AGENT_OMBRE_BACKEND:-official_with_legacy_fallback}"
# The release transaction uses this narrowly-scoped mode.  It refreshes the
# executable services while preserving the operator's existing Hermes profile
# and config.yaml shape, including arbitrary opaque MCP entries and full/lite
# membership.  Ordinary drift-repair retains the historical behaviour.
PRESERVE_RUNTIME_SHAPE="${RAN_AGENT_RELEASE_PRESERVE_RUNTIME_SHAPE:-0}"

if [ "${RAN_AGENT_NO_SUDO:-}" = "1" ] || [ "$EUID" -eq 0 ]; then
  SUDO=(env)
else
  SUDO=(sudo)
fi

cleanup() {
  rm -rf "$BACKUP_DIR"
}
trap cleanup EXIT

log() {
  printf '[hermes-runtime-split] %s\n' "$*"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1" >&2
    exit 1
  fi
}

chown_if_user_exists() {
  local path="$1"
  if id "$RUNTIME_USER" >/dev/null 2>&1; then
    "${SUDO[@]}" chown -R "$RUNTIME_USER:$RUNTIME_GROUP" "$path"
  fi
}

runtime_state_path() {
  printf '%s/%s\n' "$RUNTIME_STATE_DIR" "$1"
}

runtime_debug_path() {
  printf '%s/%s\n' "$RUNTIME_DEBUG_DIR" "$1"
}

env_file_value() {
  local file="$1"
  local key="$2"
  if "${SUDO[@]}" test -f "$file"; then
    "${SUDO[@]}" awk -F= -v key="$key" '$1 == key { value=substr($0, length(key) + 2) } END { if (value != "") print value }' "$file"
  fi
}

effective_env_value() {
  local key="$1"
  local default="$2"
  local value="${!key:-}"
  if [ -n "$value" ]; then
    printf '%s\n' "$value"
    return 0
  fi
  local file
  for file in "$NODE_ENV_FILE" "$NODE_BRIDGE_ENV_FILE" "$FULL_HOME/.env" "$LITE_HOME/.env" "$FULL_HOME/profiles/$FULL_PROFILE/.env" "$LITE_HOME/profiles/$LITE_PROFILE/.env"; do
    value="$(env_file_value "$file" "$key" | tail -n 1 || true)"
    if [ -n "$value" ]; then
      printf '%s\n' "$value"
      return 0
    fi
  done
  printf '%s\n' "$default"
}

bool_is_true() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

docker_compose_available() {
  command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1
}

ombre_brain_enabled() {
  bool_is_true "$(effective_env_value OMBRE_BRAIN_ENABLED "$OMBRE_BRAIN_ENABLED_DEFAULT")"
}

ombre_runner_value() {
  effective_env_value OMBRE_BRAIN_RUNNER "$OMBRE_BRAIN_RUNNER_DEFAULT" | tr '[:upper:]' '[:lower:]'
}

ombre_source_ready() {
  local source_dir
  local venv_dir
  source_dir="$(effective_env_value OMBRE_BRAIN_SOURCE_DIR "$OMBRE_BRAIN_SOURCE_DIR_DEFAULT")"
  venv_dir="$(effective_env_value OMBRE_BRAIN_VENV "$OMBRE_BRAIN_VENV_DEFAULT")"
  [ -f "$source_dir/src/server.py" ] && [ -x "$venv_dir/bin/python" ]
}

ombre_runner_available() {
  local status_file
  status_file="$(effective_env_value OMBRE_BRAIN_STATUS_FILE "$OMBRE_BRAIN_STATUS_FILE_DEFAULT")"
  if [ -f "$status_file" ]; then
    grep -Eq '"deploy_ready"[[:space:]]*:[[:space:]]*true' "$status_file"
    return $?
  fi
  local runner
  runner="$(ombre_runner_value)"
  case "$runner" in
    source)
      ombre_source_ready
      ;;
    docker)
      docker_compose_available
      ;;
    external)
      return 0
      ;;
    auto)
      ombre_source_ready || docker_compose_available
      ;;
    *)
      return 1
      ;;
  esac
}

ombre_mcp_should_be_exposed() {
  ombre_brain_enabled &&
    bool_is_true "$(effective_env_value OMBRE_BRAIN_MCP_ENABLED "$OMBRE_BRAIN_MCP_ENABLED_DEFAULT")" &&
    ombre_runner_available
}

trusted_runtime_media_dirs() {
  runtime_debug_path "wechat/inbound"
  runtime_debug_path "mimo_inbound"
  runtime_state_path "wechat/inbound"
  runtime_state_path "feishu/inbound"
  runtime_state_path "ran-agent-weixin/media"
}

ensure_runtime_dirs() {
  log "ensuring runtime state and trusted media directories"
  local dirs=(
    "$(runtime_state_path "uv-cache")"
    "$(runtime_state_path "uv-tools")"
    "$(runtime_state_path "social_reader")"
    "$(runtime_state_path "xhs-public-sidecar")"
    "$(runtime_state_path "environment")"
    "$OMBRE_BRAIN_HOME_DEFAULT"
    "$OMBRE_BRAIN_SOURCE_DIR_DEFAULT"
    "$OMBRE_BRAIN_VENV_DEFAULT"
    "$OMBRE_BUCKETS_DIR_DEFAULT"
  )
  local media_dir
  while IFS= read -r media_dir; do
    dirs+=("$media_dir")
  done < <(trusted_runtime_media_dirs)
  "${SUDO[@]}" mkdir -p "${dirs[@]}"
  local dir
  for dir in "${dirs[@]}"; do
    chown_if_user_exists "$dir"
  done
}

write_file() {
  local mode="$1"
  local dest="$2"
  local tmp
  tmp="$(mktemp)"
  cat >| "$tmp"
  install_file_portable "$mode" "$tmp" "$dest"
  rm -f "$tmp"
}

install_file_portable() {
  local mode="$1"
  local src="$2"
  local dest="$3"
  if "${SUDO[@]}" install -D -m "$mode" "$src" "$dest" 2>/dev/null; then
    return 0
  fi
  "${SUDO[@]}" mkdir -p "$(dirname "$dest")"
  "${SUDO[@]}" cp "$src" "$dest"
  "${SUDO[@]}" chmod "$mode" "$dest"
}

backup_env_file() {
  local label="$1"
  local file="$2"
  if "${SUDO[@]}" test -f "$file"; then
    "${SUDO[@]}" cp -p "$file" "$BACKUP_DIR/$label"
  fi
}

restore_env_file() {
  local label="$1"
  local file="$2"
  if [ -f "$BACKUP_DIR/$label" ]; then
    install_file_portable 600 "$BACKUP_DIR/$label" "$file"
    chown_if_user_exists "$file"
  fi
}

upsert_env_file() {
  local file="$1"
  shift
  local tmp
  tmp="$(mktemp)"
  local optional_key_blob=" "
  local assignment

  for assignment in "$@"; do
    if [[ "$assignment" == \?*=* ]]; then
      local optional_assignment="${assignment#\?}"
      optional_key_blob+="${optional_assignment%%=*} "
    fi
  done

  if "${SUDO[@]}" test -f "$file"; then
    while IFS= read -r line || [ -n "$line" ]; do
      local key="${line%%=*}"
      if [[ "$line" != *=* ]] || ! is_managed_env_key "$key" || [[ "$optional_key_blob" == *" $key "* ]]; then
        printf '%s\n' "$line" >> "$tmp"
      fi
    done < <("${SUDO[@]}" cat "$file")
  fi
  for assignment in "$@"; do
    if [[ "$assignment" == \?*=* ]]; then
      local default_assignment="${assignment#\?}"
      local default_key="${default_assignment%%=*}"
      if "${SUDO[@]}" test -f "$file" && "${SUDO[@]}" grep -Eq "^${default_key}=" "$file"; then
        continue
      fi
      assignment="$default_assignment"
    fi
    printf '%s\n' "$assignment" >> "$tmp"
  done
  install_file_portable 600 "$tmp" "$file"
  chown_if_user_exists "$file"
  rm -f "$tmp"
}

is_managed_env_key() {
  case "$1" in
    HERMES_HOME|HERMES_PROFILE|API_SERVER_ENABLED|API_SERVER_HOST|API_SERVER_PORT|API_SERVER_MODEL_NAME|HERMES_API_BASE_URL|HERMES_LITE_API_BASE_URL|HERMES_FULL_API_BASE_URL|HERMES_LITE_PROFILE|HERMES_FULL_PROFILE|RAN_AGENT_CAPABILITY_MODE|RAN_AGENT_INTERNAL_CONTROL_SECRET|HERMES_CONTEXT_INJECTION_MODE|HERMES_CONTEXT_CACHE_STRATEGY|HERMES_SESSION_CONTINUITY_ENABLED|HERMES_SESSION_ID_PREFIX|HERMES_SESSION_KEY_PREFIX|HERMES_RECENT_TEXT_TURNS|HERMES_RECENT_TEXT_CHAR_BUDGET|HERMES_RECENT_TEXT_MAX_USER_CHARS|HERMES_RECENT_TEXT_MAX_ASSISTANT_CHARS|HERMES_GLOBAL_RECENT_TURNS|HERMES_GLOBAL_RECENT_CHAR_BUDGET|HERMES_ACTIVE_TOPIC_CHAR_BUDGET|HERMES_CONTINUITY_FRESHNESS_HOURS|HERMES_CACHE_FRIENDLY_HISTORY|HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS|HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET|HERMES_CACHE_FRIENDLY_HISTORY_PROFILE|HERMES_CACHE_TELEMETRY_ENABLED|HERMES_LITE_SOFT_RESET_ENABLED|HERMES_LITE_SOFT_RESET_DRY_RUN|HERMES_LITE_SOFT_RESET_MAX_DIGEST_CHARS|HERMES_LITE_SOFT_RESET_KEEP_LAST_N|HERMES_LITE_SOFT_RESET_STATE_FILE|HERMES_LITE_SOFT_RESET_DIGEST_DIR|HERMES_ACTION_GATE_ENABLED|HERMES_ACTION_GATE_MODE|HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS|HERMES_ACTION_PENDING_ENABLED|HERMES_ACTION_PENDING_TTL_MINUTES|HERMES_REPLY_TIMEOUT_SECONDS|NODE_BRIDGE_QUICK_ACK_ENABLED|NODE_BRIDGE_QUICK_ACK_TIMEOUT_MS|NODE_BRIDGE_QUICK_ACK_TEXT|FEISHU_SEND_TIMEOUT_SECONDS|FEISHU_DOWNLOAD_TIMEOUT_SECONDS|HERMES_ENVIRONMENT_CONTEXT_ENABLED|HERMES_ENVIRONMENT_WEATHER_ENABLED|HERMES_ENVIRONMENT_MAX_AGE_MS|HERMES_ENVIRONMENT_WEATHER_CACHE_MS|HERMES_ENVIRONMENT_TIMEZONE|RAN_AGENT_TIMELINE_MAX_BYTES|RAN_AGENT_TIMELINE_MAX_TURNS|RAN_AGENT_TIMELINE_RETENTION_DAYS|RAN_AGENT_TIMELINE_COMPACT_ENABLED|RAN_AGENT_TIMELINE_ARCHIVE_DIR|PERSONAL_AGENT_PROACTIVE_ENABLED|PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED|HERMES_PROACTIVE_EVENTS_ENABLED|HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED|HERMES_PROACTIVE_REMINDERS_ENABLED|HERMES_PROACTIVE_NOTIFY_MAX_CHARS|PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS|PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS|PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE|PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED|PERSONAL_AGENT_DAILY_CARRYOVER_HOUR|PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE|AI_DAILY_DIGEST_ENABLED|AI_DAILY_DIGEST_HOUR|AI_DAILY_DIGEST_MINUTE|FEISHU_LARK_CLI_BIN|FEISHU_LARK_CLI_IDENTITY|DESKTOP_PROXY_HOST|DESKTOP_PROXY_PORT|SEARCH_HUB_ENABLED|SEARCH_HUB_PROFILE_MODE|SEARCH_HUB_DEFAULT_LIMIT|SEARCH_HUB_TIMEOUT_MS|SEARCH_HUB_CACHE_TTL_MS|SEARCH_HUB_CACHE_PATH|SEARCH_HUB_ENABLE_TAVILY|SEARCH_HUB_ENABLE_AIHOT|SEARCH_HUB_ENABLE_OPENCLI|SEARCH_HUB_ENABLE_OPENCLI_BROWSER|SEARCH_HUB_ENABLE_PLAYWRIGHT_FALLBACK|SEARCH_HUB_OPENCLI_BIN|SEARCH_HUB_OPENCLI_TIMEOUT_MS|SEARCH_HUB_PUBLIC_ONLY_DEFAULT|UV_CACHE_DIR|UV_TOOL_DIR|UV_LINK_MODE|UV_PYTHON_DOWNLOADS|SOCIAL_READER_GENERIC_FALLBACK_ENABLED|SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS|SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS|XHS_BACKEND_MCP_TIMEOUT_MS|MEDIA_READER_MCP_TIMEOUT_MS|PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS|PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY|PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS|PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS|PERSONAL_AGENT_OCR_PROVIDER|PERSONAL_AGENT_OCR_MODEL|PERSONAL_AGENT_OCR_TIMEOUT_MS|OBSIDIAN_MEMORY_MCP_ENABLED|XHS_GENERIC_FALLBACK_READY_PATH|XHS_GENERIC_FALLBACK_MIN_VERSION|XHS_PUBLIC_SIDECAR_ENABLED|XHS_PUBLIC_SIDECAR_URL|XHS_PUBLIC_SIDECAR_TIMEOUT_MS|XHS_PUBLIC_HTML_FALLBACK_ENABLED|XHS_PUBLIC_SIDECAR_MARKER_PATH|XHS_PUBLIC_SIDECAR_ROOT_DIR|WEIXIN_SDK_INBOUND_MEDIA_DIRS|EXTERNAL_MCP_GATEWAY_PROFILE|EXTERNAL_MCP_GATEWAY_ALLOW_ENV_ENABLE|EXTERNAL_MCP_GATEWAY_ENABLED|EXTERNAL_MCP_SYSTEM_QUEUE_ENABLED|EXTERNAL_MCP_ACTIVITY_RUNNER_ENABLED|EXTERNAL_MCP_ACTIVITY_TICK_MS|OMBRE_BRAIN_ENABLED|OMBRE_BRAIN_MCP_ENABLED|OMBRE_BRAIN_RUNNER|OMBRE_BRAIN_REPO_URL|OMBRE_BRAIN_HOME|OMBRE_BRAIN_SOURCE_DIR|OMBRE_BRAIN_VENV|OMBRE_BUCKETS_DIR|OMBRE_BRAIN_IMAGE|OMBRE_BRAIN_BIND_HOST|OMBRE_BRAIN_PORT|OMBRE_BRAIN_COMPOSE_FILE|OMBRE_BRAIN_CONFIG_FILE|OMBRE_BRAIN_STATUS_FILE|OMBRE_BRAIN_MCP_URL|OMBRE_BRAIN_MCP_EXTRA_URL|OMBRE_BRAIN_HEALTH_URL|PERSONAL_AGENT_OMBRE_BACKEND|PERSONAL_AGENT_OMBRE_MCP_URL|PERSONAL_AGENT_OMBRE_MCP_EXTRA_URL|PERSONAL_AGENT_OMBRE_MCP_TIMEOUT_SECONDS|PERSONAL_AGENT_OMBRE_READ_ENABLED|PERSONAL_AGENT_OMBRE_WRITE_ENABLED|PERSONAL_AGENT_OMBRE_TIMEOUT_MS|PERSONAL_AGENT_OMBRE_MAX_RESULTS|PERSONAL_AGENT_OMBRE_MAX_CHARS|PERSONAL_AGENT_OMBRE_ANCHOR_ENABLED|PERSONAL_AGENT_OMBRE_I_ENABLED|PERSONAL_AGENT_OMBRE_WRITE_MODE)
      return 0
      ;;
    XHS_COOKIE|XHS_MCP_COMMAND|XHS_MCP_ARGS_JSON|PERSONAL_AGENT_XHS_MCP_COMMAND|PERSONAL_AGENT_XHS_MCP_ARGS_JSON|XHS_BROWSE_ENABLED|SOCIAL_READER_EXPOSE_XHS_BROWSE_TOOLS|XHS_BROWSE_MARKER_PATH|XHS_BROWSE_ROOT_DIR|XHS_BROWSE_MCP_URL|XHS_BROWSE_MCP_COMMAND|XHS_BROWSE_MCP_ARGS_JSON|XHS_BROWSE_MCP_COOKIE_ENV|XHS_BROWSE_MCP_COOKIE|XHS_BROWSE_MCP_TIMEOUT_MS|XHS_BROWSE_MAX_RESULTS|XHS_BROWSE_MAX_ITEMS|XHS_BROWSE_MIN_INTERVAL_MS|XHS_BROWSE_MAX_CALLS_PER_SESSION|XHS_BROWSE_SEARCH_ENABLED|XHS_BROWSE_NOTE_ENABLED|XHS_BROWSE_USER_ENABLED|XHS_BROWSE_FEED_ENABLED|XHS_NOTE_TOKEN_CACHE_PATH|XHS_NOTE_TOKEN_CACHE_DEBUG)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

install_profiles() {
  log "installing Hermes profiles"
  mkdir -p "$FULL_HOME" "$LITE_HOME"
  chown_if_user_exists "$FULL_HOME"

  HERMES_HOME="$FULL_HOME" "$HERMES_BIN" profile install "$REPO_ROOT/hermes/profile" --name "$FULL_PROFILE" --force -y
  HERMES_HOME="$LITE_HOME" "$HERMES_BIN" profile install "$REPO_ROOT/hermes/profile" --name "$LITE_PROFILE" --force -y
}

write_runtime_env() {
  log "refreshing runtime env files without touching secrets"
  local internal_control_secret="${RAN_AGENT_DEPLOY_INTERNAL_CONTROL_SECRET:-}"
  if [[ ! "$internal_control_secret" =~ ^[a-f0-9]{64}$ ]] && "${SUDO[@]}" test -f "$NODE_ENV_FILE"; then
    internal_control_secret="$("${SUDO[@]}" sed -n 's/^RAN_AGENT_INTERNAL_CONTROL_SECRET=//p' "$NODE_ENV_FILE" | tail -n 1)"
  fi
  if [[ ! "$internal_control_secret" =~ ^[a-f0-9]{64}$ ]]; then
    internal_control_secret="$(openssl rand -hex 32)"
  fi
  local ombre_env=(
    "?OMBRE_BRAIN_ENABLED=$OMBRE_BRAIN_ENABLED_DEFAULT"
    "?OMBRE_BRAIN_MCP_ENABLED=$OMBRE_BRAIN_MCP_ENABLED_DEFAULT"
    "?OMBRE_BRAIN_RUNNER=$OMBRE_BRAIN_RUNNER_DEFAULT"
    "?OMBRE_BRAIN_REPO_URL=$OMBRE_BRAIN_REPO_URL_DEFAULT"
    "?OMBRE_BRAIN_HOME=$OMBRE_BRAIN_HOME_DEFAULT"
    "?OMBRE_BRAIN_SOURCE_DIR=$OMBRE_BRAIN_SOURCE_DIR_DEFAULT"
    "?OMBRE_BRAIN_VENV=$OMBRE_BRAIN_VENV_DEFAULT"
    "?OMBRE_BUCKETS_DIR=$OMBRE_BUCKETS_DIR_DEFAULT"
    "?OMBRE_BRAIN_IMAGE=$OMBRE_BRAIN_IMAGE_DEFAULT"
    "?OMBRE_BRAIN_BIND_HOST=$OMBRE_BRAIN_BIND_HOST_DEFAULT"
    "?OMBRE_BRAIN_PORT=$OMBRE_BRAIN_PORT_DEFAULT"
    "?OMBRE_BRAIN_COMPOSE_FILE=$OMBRE_BRAIN_COMPOSE_FILE_DEFAULT"
    "?OMBRE_BRAIN_CONFIG_FILE=$OMBRE_BRAIN_CONFIG_FILE_DEFAULT"
    "?OMBRE_BRAIN_STATUS_FILE=$OMBRE_BRAIN_STATUS_FILE_DEFAULT"
    "?OMBRE_BRAIN_MCP_URL=$OMBRE_BRAIN_MCP_URL_DEFAULT"
    "?OMBRE_BRAIN_MCP_EXTRA_URL=$OMBRE_BRAIN_MCP_EXTRA_URL_DEFAULT"
    "?OMBRE_BRAIN_HEALTH_URL=$OMBRE_BRAIN_HEALTH_URL_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_BACKEND=$PERSONAL_AGENT_OMBRE_BACKEND_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_MCP_URL=$OMBRE_BRAIN_MCP_URL_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_MCP_EXTRA_URL=$OMBRE_BRAIN_MCP_EXTRA_URL_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_MCP_TIMEOUT_SECONDS=10"
    "?PERSONAL_AGENT_OMBRE_READ_ENABLED=$PERSONAL_AGENT_OMBRE_READ_ENABLED_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_WRITE_ENABLED=$PERSONAL_AGENT_OMBRE_WRITE_ENABLED_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_TIMEOUT_MS=$PERSONAL_AGENT_OMBRE_TIMEOUT_MS_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_MAX_RESULTS=$PERSONAL_AGENT_OMBRE_MAX_RESULTS_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_MAX_CHARS=$PERSONAL_AGENT_OMBRE_MAX_CHARS_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_ANCHOR_ENABLED=$PERSONAL_AGENT_OMBRE_ANCHOR_ENABLED_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_I_ENABLED=$PERSONAL_AGENT_OMBRE_I_ENABLED_DEFAULT"
    "?PERSONAL_AGENT_OMBRE_WRITE_MODE=$PERSONAL_AGENT_OMBRE_WRITE_MODE_DEFAULT"
  )
  local xhs_public_env=(
    "XHS_PUBLIC_SIDECAR_ENABLED=$XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT"
    "XHS_PUBLIC_SIDECAR_URL=$XHS_PUBLIC_SIDECAR_URL_DEFAULT"
    "XHS_PUBLIC_SIDECAR_TIMEOUT_MS=$XHS_PUBLIC_SIDECAR_TIMEOUT_MS_DEFAULT"
    "XHS_PUBLIC_HTML_FALLBACK_ENABLED=$XHS_PUBLIC_HTML_FALLBACK_ENABLED_DEFAULT"
    "XHS_PUBLIC_SIDECAR_MARKER_PATH=$XHS_PUBLIC_SIDECAR_MARKER_PATH_DEFAULT"
    "XHS_PUBLIC_SIDECAR_ROOT_DIR=$XHS_PUBLIC_SIDECAR_ROOT_DIR_DEFAULT"
  )
  local media_reader_ocr_env=(
    "PERSONAL_AGENT_OCR_PROVIDER=$PERSONAL_AGENT_OCR_PROVIDER_DEFAULT"
    "PERSONAL_AGENT_OCR_MODEL=$PERSONAL_AGENT_OCR_MODEL_DEFAULT"
    "PERSONAL_AGENT_OCR_TIMEOUT_MS=$PERSONAL_AGENT_OCR_TIMEOUT_MS_DEFAULT"
  )
  local external_mcp_env=(
    "EXTERNAL_MCP_GATEWAY_ALLOW_ENV_ENABLE=$EXTERNAL_MCP_GATEWAY_ALLOW_ENV_ENABLE_DEFAULT"
    "EXTERNAL_MCP_GATEWAY_ENABLED=$EXTERNAL_MCP_GATEWAY_ENABLED_DEFAULT"
    "EXTERNAL_MCP_SYSTEM_QUEUE_ENABLED=$EXTERNAL_MCP_SYSTEM_QUEUE_ENABLED_DEFAULT"
    "EXTERNAL_MCP_ACTIVITY_RUNNER_ENABLED=$EXTERNAL_MCP_ACTIVITY_RUNNER_ENABLED_DEFAULT"
    "EXTERNAL_MCP_ACTIVITY_TICK_MS=$EXTERNAL_MCP_ACTIVITY_TICK_MS_DEFAULT"
  )
  local hermes_client_env=(
    "HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT"
  )
  local reply_window_env=(
    "${hermes_client_env[@]}"
    "NODE_BRIDGE_QUICK_ACK_ENABLED=$NODE_BRIDGE_QUICK_ACK_ENABLED_DEFAULT"
    "NODE_BRIDGE_QUICK_ACK_TIMEOUT_MS=$NODE_BRIDGE_QUICK_ACK_TIMEOUT_MS_DEFAULT"
    "NODE_BRIDGE_QUICK_ACK_TEXT=$NODE_BRIDGE_QUICK_ACK_TEXT_DEFAULT"
    "FEISHU_SEND_TIMEOUT_SECONDS=$FEISHU_SEND_TIMEOUT_SECONDS_DEFAULT"
    "FEISHU_DOWNLOAD_TIMEOUT_SECONDS=$FEISHU_DOWNLOAD_TIMEOUT_SECONDS_DEFAULT"
  )
  local proactive_event_env=(
    "HERMES_PROACTIVE_EVENTS_ENABLED=$HERMES_PROACTIVE_EVENTS_ENABLED_DEFAULT"
    "HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED=$HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED_DEFAULT"
    "HERMES_PROACTIVE_REMINDERS_ENABLED=$HERMES_PROACTIVE_REMINDERS_ENABLED_DEFAULT"
    "HERMES_PROACTIVE_NOTIFY_MAX_CHARS=$HERMES_PROACTIVE_NOTIFY_MAX_CHARS_DEFAULT"
  )
  upsert_env_file "$FULL_HOME/.env" \
    "HERMES_HOME=$FULL_HOME" \
    "HERMES_PROFILE=$FULL_PROFILE" \
    "API_SERVER_ENABLED=true" \
    "API_SERVER_HOST=$API_HOST" \
    "API_SERVER_PORT=$FULL_PORT" \
    "API_SERVER_MODEL_NAME=$FULL_PROFILE" \
    "HERMES_API_BASE_URL=http://$API_HOST:$FULL_PORT/v1" \
    "${hermes_client_env[@]}" \
    "PERSONAL_AGENT_PROACTIVE_ENABLED=false" \
    "PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED=false" \
    "${proactive_event_env[@]}" \
    "${external_mcp_env[@]}" \
    "EXTERNAL_MCP_GATEWAY_PROFILE=full" \
    "PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS=$PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS_DEFAULT" \
    "PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS=$PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS_DEFAULT" \
    "PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE=$PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED=$PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_HOUR=$PERSONAL_AGENT_DAILY_CARRYOVER_HOUR_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE=$PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE_DEFAULT" \
    "SEARCH_HUB_ENABLED=true" \
    "SEARCH_HUB_PROFILE_MODE=full" \
    "SEARCH_HUB_DEFAULT_LIMIT=5" \
    "SEARCH_HUB_TIMEOUT_MS=30000" \
    "SEARCH_HUB_CACHE_TTL_MS=300000" \
    "SEARCH_HUB_CACHE_PATH=/opt/ran_agent/.ran_agent_state/search_hub/cache.jsonl" \
    "SEARCH_HUB_ENABLE_TAVILY=true" \
    "SEARCH_HUB_ENABLE_AIHOT=true" \
    "SEARCH_HUB_ENABLE_OPENCLI=true" \
    "SEARCH_HUB_ENABLE_OPENCLI_BROWSER=false" \
    "SEARCH_HUB_ENABLE_PLAYWRIGHT_FALLBACK=true" \
    "SEARCH_HUB_OPENCLI_BIN=opencli" \
    "SEARCH_HUB_OPENCLI_TIMEOUT_MS=60000" \
    "SEARCH_HUB_PUBLIC_ONLY_DEFAULT=false" \
    "UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache" \
    "UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools" \
    "UV_LINK_MODE=copy" \
    "UV_PYTHON_DOWNLOADS=never" \
    "SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true" \
    "SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000" \
    "?SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000" \
    "XHS_BACKEND_MCP_TIMEOUT_MS=90000" \
    "MEDIA_READER_MCP_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000" \
    "PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3" \
    "PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000" \
    "${media_reader_ocr_env[@]}" \
    "OBSIDIAN_MEMORY_MCP_ENABLED=false" \
    "XHS_GENERIC_FALLBACK_READY_PATH=/opt/ran_agent/.ran_agent_state/social_reader/generic-fallback-ready.json" \
    "?XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0" \
    "WEIXIN_SDK_INBOUND_MEDIA_DIRS=$WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT" \
    "${xhs_public_env[@]}" \
    "${ombre_env[@]}" \
    "?OPENALEX_MAILTO="

  upsert_env_file "$FULL_HOME/profiles/$FULL_PROFILE/.env" \
    "HERMES_HOME=$FULL_HOME" \
    "HERMES_PROFILE=$FULL_PROFILE" \
    "API_SERVER_ENABLED=true" \
    "API_SERVER_HOST=$API_HOST" \
    "API_SERVER_PORT=$FULL_PORT" \
    "API_SERVER_MODEL_NAME=$FULL_PROFILE" \
    "HERMES_API_BASE_URL=http://$API_HOST:$FULL_PORT/v1" \
    "${hermes_client_env[@]}" \
    "PERSONAL_AGENT_PROACTIVE_ENABLED=false" \
    "PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED=false" \
    "${proactive_event_env[@]}" \
    "${external_mcp_env[@]}" \
    "EXTERNAL_MCP_GATEWAY_PROFILE=full" \
    "SEARCH_HUB_ENABLED=true" \
    "SEARCH_HUB_PROFILE_MODE=full" \
    "SEARCH_HUB_DEFAULT_LIMIT=5" \
    "SEARCH_HUB_TIMEOUT_MS=30000" \
    "SEARCH_HUB_CACHE_TTL_MS=300000" \
    "SEARCH_HUB_CACHE_PATH=/opt/ran_agent/.ran_agent_state/search_hub/cache.jsonl" \
    "SEARCH_HUB_ENABLE_TAVILY=true" \
    "SEARCH_HUB_ENABLE_AIHOT=true" \
    "SEARCH_HUB_ENABLE_OPENCLI=true" \
    "SEARCH_HUB_ENABLE_OPENCLI_BROWSER=false" \
    "SEARCH_HUB_ENABLE_PLAYWRIGHT_FALLBACK=true" \
    "SEARCH_HUB_OPENCLI_BIN=opencli" \
    "SEARCH_HUB_OPENCLI_TIMEOUT_MS=60000" \
    "SEARCH_HUB_PUBLIC_ONLY_DEFAULT=false" \
    "UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache" \
    "UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools" \
    "UV_LINK_MODE=copy" \
    "UV_PYTHON_DOWNLOADS=never" \
    "SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true" \
    "SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000" \
    "?SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000" \
    "XHS_BACKEND_MCP_TIMEOUT_MS=90000" \
    "MEDIA_READER_MCP_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000" \
    "PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3" \
    "PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000" \
    "${media_reader_ocr_env[@]}" \
    "OBSIDIAN_MEMORY_MCP_ENABLED=false" \
    "XHS_GENERIC_FALLBACK_READY_PATH=/opt/ran_agent/.ran_agent_state/social_reader/generic-fallback-ready.json" \
    "?XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0" \
    "WEIXIN_SDK_INBOUND_MEDIA_DIRS=$WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT" \
    "${xhs_public_env[@]}" \
    "${ombre_env[@]}" \
    "?OPENALEX_MAILTO="

  upsert_env_file "$LITE_HOME/.env" \
    "HERMES_HOME=$LITE_HOME" \
    "HERMES_PROFILE=$LITE_PROFILE" \
    "API_SERVER_ENABLED=true" \
    "API_SERVER_HOST=$API_HOST" \
    "API_SERVER_PORT=$LITE_PORT" \
    "API_SERVER_MODEL_NAME=$LITE_PROFILE" \
    "HERMES_API_BASE_URL=http://$API_HOST:$LITE_PORT/v1" \
    "${hermes_client_env[@]}" \
    "PERSONAL_AGENT_PROACTIVE_ENABLED=false" \
    "PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED=false" \
    "${proactive_event_env[@]}" \
    "${external_mcp_env[@]}" \
    "EXTERNAL_MCP_GATEWAY_PROFILE=lite" \
    "SEARCH_HUB_ENABLED=true" \
    "SEARCH_HUB_PROFILE_MODE=lite" \
    "SEARCH_HUB_DEFAULT_LIMIT=5" \
    "SEARCH_HUB_TIMEOUT_MS=30000" \
    "SEARCH_HUB_CACHE_TTL_MS=300000" \
    "SEARCH_HUB_CACHE_PATH=/opt/ran_agent/.ran_agent_state/search_hub/cache.jsonl" \
    "SEARCH_HUB_ENABLE_TAVILY=true" \
    "SEARCH_HUB_ENABLE_AIHOT=true" \
    "SEARCH_HUB_ENABLE_OPENCLI=true" \
    "SEARCH_HUB_ENABLE_OPENCLI_BROWSER=false" \
    "SEARCH_HUB_ENABLE_PLAYWRIGHT_FALLBACK=false" \
    "SEARCH_HUB_OPENCLI_BIN=opencli" \
    "SEARCH_HUB_OPENCLI_TIMEOUT_MS=60000" \
    "SEARCH_HUB_PUBLIC_ONLY_DEFAULT=true" \
    "UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache" \
    "UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools" \
    "UV_LINK_MODE=copy" \
    "UV_PYTHON_DOWNLOADS=never" \
    "SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true" \
    "SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000" \
    "?SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000" \
    "XHS_BACKEND_MCP_TIMEOUT_MS=90000" \
    "MEDIA_READER_MCP_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000" \
    "PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3" \
    "PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000" \
    "${media_reader_ocr_env[@]}" \
    "OBSIDIAN_MEMORY_MCP_ENABLED=false" \
    "XHS_GENERIC_FALLBACK_READY_PATH=/opt/ran_agent/.ran_agent_state/social_reader/generic-fallback-ready.json" \
    "?XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0" \
    "WEIXIN_SDK_INBOUND_MEDIA_DIRS=$WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT" \
    "${xhs_public_env[@]}" \
    "${ombre_env[@]}" \
    "?OPENALEX_MAILTO="

  upsert_env_file "$LITE_HOME/profiles/$LITE_PROFILE/.env" \
    "HERMES_HOME=$LITE_HOME" \
    "HERMES_PROFILE=$LITE_PROFILE" \
    "API_SERVER_ENABLED=true" \
    "API_SERVER_HOST=$API_HOST" \
    "API_SERVER_PORT=$LITE_PORT" \
    "API_SERVER_MODEL_NAME=$LITE_PROFILE" \
    "HERMES_API_BASE_URL=http://$API_HOST:$LITE_PORT/v1" \
    "${hermes_client_env[@]}" \
    "PERSONAL_AGENT_PROACTIVE_ENABLED=false" \
    "PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED=false" \
    "${proactive_event_env[@]}" \
    "${external_mcp_env[@]}" \
    "EXTERNAL_MCP_GATEWAY_PROFILE=lite" \
    "SEARCH_HUB_ENABLED=true" \
    "SEARCH_HUB_PROFILE_MODE=lite" \
    "SEARCH_HUB_DEFAULT_LIMIT=5" \
    "SEARCH_HUB_TIMEOUT_MS=30000" \
    "SEARCH_HUB_CACHE_TTL_MS=300000" \
    "SEARCH_HUB_CACHE_PATH=/opt/ran_agent/.ran_agent_state/search_hub/cache.jsonl" \
    "SEARCH_HUB_ENABLE_TAVILY=true" \
    "SEARCH_HUB_ENABLE_AIHOT=true" \
    "SEARCH_HUB_ENABLE_OPENCLI=true" \
    "SEARCH_HUB_ENABLE_OPENCLI_BROWSER=false" \
    "SEARCH_HUB_ENABLE_PLAYWRIGHT_FALLBACK=false" \
    "SEARCH_HUB_OPENCLI_BIN=opencli" \
    "SEARCH_HUB_OPENCLI_TIMEOUT_MS=60000" \
    "SEARCH_HUB_PUBLIC_ONLY_DEFAULT=true" \
    "UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache" \
    "UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools" \
    "UV_LINK_MODE=copy" \
    "UV_PYTHON_DOWNLOADS=never" \
    "SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true" \
    "SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000" \
    "?SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000" \
    "XHS_BACKEND_MCP_TIMEOUT_MS=90000" \
    "MEDIA_READER_MCP_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000" \
    "PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3" \
    "PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000" \
    "${media_reader_ocr_env[@]}" \
    "OBSIDIAN_MEMORY_MCP_ENABLED=false" \
    "XHS_GENERIC_FALLBACK_READY_PATH=/opt/ran_agent/.ran_agent_state/social_reader/generic-fallback-ready.json" \
    "?XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0" \
    "WEIXIN_SDK_INBOUND_MEDIA_DIRS=$WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT" \
    "${xhs_public_env[@]}" \
    "${ombre_env[@]}" \
    "?OPENALEX_MAILTO="

  upsert_env_file "$NODE_ENV_FILE" \
    "RAN_AGENT_INTERNAL_CONTROL_SECRET=$internal_control_secret" \
    "HERMES_API_BASE_URL=http://$API_HOST:$LITE_PORT/v1" \
    "HERMES_LITE_API_BASE_URL=http://$API_HOST:$LITE_PORT/v1" \
    "HERMES_FULL_API_BASE_URL=http://$API_HOST:$FULL_PORT/v1" \
    "RAN_AGENT_CAPABILITY_MODE=auto" \
    "HERMES_CONTEXT_INJECTION_MODE=$HERMES_CONTEXT_INJECTION_MODE_DEFAULT" \
    "HERMES_CONTEXT_CACHE_STRATEGY=$HERMES_CONTEXT_CACHE_STRATEGY_DEFAULT" \
    "HERMES_LITE_PROFILE=$LITE_PROFILE" \
    "HERMES_FULL_PROFILE=$FULL_PROFILE" \
    "HERMES_SESSION_CONTINUITY_ENABLED=true" \
    "HERMES_SESSION_ID_PREFIX=ran-agent" \
    "HERMES_SESSION_KEY_PREFIX=ran-agent-memory" \
    "HERMES_RECENT_TEXT_TURNS=$HERMES_RECENT_TEXT_TURNS_DEFAULT" \
    "HERMES_RECENT_TEXT_CHAR_BUDGET=$HERMES_RECENT_TEXT_CHAR_BUDGET_DEFAULT" \
    "HERMES_RECENT_TEXT_MAX_USER_CHARS=1200" \
    "HERMES_RECENT_TEXT_MAX_ASSISTANT_CHARS=1200" \
    "HERMES_GLOBAL_RECENT_TURNS=$HERMES_GLOBAL_RECENT_TURNS_DEFAULT" \
    "HERMES_GLOBAL_RECENT_CHAR_BUDGET=$HERMES_GLOBAL_RECENT_CHAR_BUDGET_DEFAULT" \
    "HERMES_ACTIVE_TOPIC_CHAR_BUDGET=$HERMES_ACTIVE_TOPIC_CHAR_BUDGET_DEFAULT" \
    "HERMES_CONTINUITY_FRESHNESS_HOURS=$HERMES_CONTINUITY_FRESHNESS_HOURS_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY=$HERMES_CACHE_FRIENDLY_HISTORY_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS=$HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET=$HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_PROFILE=$HERMES_CACHE_FRIENDLY_HISTORY_PROFILE_DEFAULT" \
    "HERMES_CACHE_TELEMETRY_ENABLED=$HERMES_CACHE_TELEMETRY_ENABLED_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_ENABLED=$HERMES_LITE_SOFT_RESET_ENABLED_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_DRY_RUN=$HERMES_LITE_SOFT_RESET_DRY_RUN_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_MAX_DIGEST_CHARS=$HERMES_LITE_SOFT_RESET_MAX_DIGEST_CHARS_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_KEEP_LAST_N=$HERMES_LITE_SOFT_RESET_KEEP_LAST_N_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_STATE_FILE=$HERMES_LITE_SOFT_RESET_STATE_FILE_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_DIGEST_DIR=$HERMES_LITE_SOFT_RESET_DIGEST_DIR_DEFAULT" \
    "HERMES_ACTION_GATE_ENABLED=$HERMES_ACTION_GATE_ENABLED_DEFAULT" \
    "HERMES_ACTION_GATE_MODE=$HERMES_ACTION_GATE_MODE_DEFAULT" \
    "HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS=$HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS_DEFAULT" \
    "HERMES_ACTION_PENDING_ENABLED=$HERMES_ACTION_PENDING_ENABLED_DEFAULT" \
    "HERMES_ACTION_PENDING_TTL_MINUTES=$HERMES_ACTION_PENDING_TTL_MINUTES_DEFAULT" \
    "${reply_window_env[@]}" \
    "HERMES_CONTINUITY_FRESHNESS_HOURS=$HERMES_CONTINUITY_FRESHNESS_HOURS_DEFAULT" \
    "?HERMES_ENVIRONMENT_CONTEXT_ENABLED=$HERMES_ENVIRONMENT_CONTEXT_ENABLED_DEFAULT" \
    "?HERMES_ENVIRONMENT_WEATHER_ENABLED=$HERMES_ENVIRONMENT_WEATHER_ENABLED_DEFAULT" \
    "?HERMES_ENVIRONMENT_MAX_AGE_MS=$HERMES_ENVIRONMENT_MAX_AGE_MS_DEFAULT" \
    "?HERMES_ENVIRONMENT_WEATHER_CACHE_MS=$HERMES_ENVIRONMENT_WEATHER_CACHE_MS_DEFAULT" \
    "?HERMES_ENVIRONMENT_TIMEZONE=$HERMES_ENVIRONMENT_TIMEZONE_DEFAULT" \
    "RAN_AGENT_TIMELINE_MAX_BYTES=52428800" \
    "RAN_AGENT_TIMELINE_MAX_TURNS=5000" \
    "RAN_AGENT_TIMELINE_RETENTION_DAYS=30" \
    "RAN_AGENT_TIMELINE_COMPACT_ENABLED=true" \
    "RAN_AGENT_TIMELINE_ARCHIVE_DIR=/opt/ran_agent/.ran_agent_state/timeline_archive" \
    "PERSONAL_AGENT_PROACTIVE_ENABLED=false" \
    "PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED=false" \
    "${proactive_event_env[@]}" \
    "${external_mcp_env[@]}" \
    "PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS=$PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS_DEFAULT" \
    "PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS=$PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS_DEFAULT" \
    "PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE=$PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED=$PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_HOUR=$PERSONAL_AGENT_DAILY_CARRYOVER_HOUR_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE=$PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE_DEFAULT" \
    "AI_DAILY_DIGEST_ENABLED=$AI_DAILY_DIGEST_ENABLED_DEFAULT" \
    "AI_DAILY_DIGEST_HOUR=$AI_DAILY_DIGEST_HOUR_DEFAULT" \
    "AI_DAILY_DIGEST_MINUTE=$AI_DAILY_DIGEST_MINUTE_DEFAULT" \
    "SEARCH_HUB_ENABLED=true" \
    "SEARCH_HUB_DEFAULT_LIMIT=5" \
    "SEARCH_HUB_TIMEOUT_MS=30000" \
    "SEARCH_HUB_CACHE_TTL_MS=300000" \
    "SEARCH_HUB_CACHE_PATH=/opt/ran_agent/.ran_agent_state/search_hub/cache.jsonl" \
    "SEARCH_HUB_ENABLE_TAVILY=true" \
    "SEARCH_HUB_ENABLE_AIHOT=true" \
    "SEARCH_HUB_ENABLE_OPENCLI=true" \
    "SEARCH_HUB_OPENCLI_BIN=opencli" \
    "SEARCH_HUB_OPENCLI_TIMEOUT_MS=60000" \
    "?OPENALEX_MAILTO=" \
    "?FEISHU_BRIDGE_ENABLED=false" \
    "FEISHU_LARK_CLI_BIN=lark-cli" \
    "FEISHU_LARK_CLI_IDENTITY=bot" \
    "?DESKTOP_PROXY_ENABLED=false" \
    "DESKTOP_PROXY_HOST=127.0.0.1" \
    "DESKTOP_PROXY_PORT=8650" \
    "UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache" \
    "UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools" \
    "UV_LINK_MODE=copy" \
    "UV_PYTHON_DOWNLOADS=never" \
    "SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true" \
    "SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000" \
    "?SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000" \
    "XHS_BACKEND_MCP_TIMEOUT_MS=90000" \
    "MEDIA_READER_MCP_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000" \
    "PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3" \
    "PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000" \
    "${media_reader_ocr_env[@]}" \
    "OBSIDIAN_MEMORY_MCP_ENABLED=false" \
    "XHS_GENERIC_FALLBACK_READY_PATH=/opt/ran_agent/.ran_agent_state/social_reader/generic-fallback-ready.json" \
    "?XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0" \
    "WEIXIN_SDK_INBOUND_MEDIA_DIRS=$WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT" \
    "${xhs_public_env[@]}" \
    "${ombre_env[@]}"

  upsert_env_file "$NODE_BRIDGE_ENV_FILE" \
    "HERMES_CONTEXT_CACHE_STRATEGY=$HERMES_CONTEXT_CACHE_STRATEGY_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY=$HERMES_CACHE_FRIENDLY_HISTORY_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS=$HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET=$HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_PROFILE=$HERMES_CACHE_FRIENDLY_HISTORY_PROFILE_DEFAULT" \
    "HERMES_CACHE_TELEMETRY_ENABLED=$HERMES_CACHE_TELEMETRY_ENABLED_DEFAULT" \
    "HERMES_ACTION_GATE_ENABLED=$HERMES_ACTION_GATE_ENABLED_DEFAULT" \
    "HERMES_ACTION_GATE_MODE=$HERMES_ACTION_GATE_MODE_DEFAULT" \
    "HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS=$HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS_DEFAULT" \
    "HERMES_ACTION_PENDING_ENABLED=$HERMES_ACTION_PENDING_ENABLED_DEFAULT" \
    "HERMES_ACTION_PENDING_TTL_MINUTES=$HERMES_ACTION_PENDING_TTL_MINUTES_DEFAULT" \
    "${reply_window_env[@]}" \
    "PERSONAL_AGENT_PROACTIVE_ENABLED=false" \
    "?HERMES_ENVIRONMENT_CONTEXT_ENABLED=$HERMES_ENVIRONMENT_CONTEXT_ENABLED_DEFAULT" \
    "?HERMES_ENVIRONMENT_WEATHER_ENABLED=$HERMES_ENVIRONMENT_WEATHER_ENABLED_DEFAULT" \
    "?HERMES_ENVIRONMENT_MAX_AGE_MS=$HERMES_ENVIRONMENT_MAX_AGE_MS_DEFAULT" \
    "?HERMES_ENVIRONMENT_WEATHER_CACHE_MS=$HERMES_ENVIRONMENT_WEATHER_CACHE_MS_DEFAULT" \
    "?HERMES_ENVIRONMENT_TIMEZONE=$HERMES_ENVIRONMENT_TIMEZONE_DEFAULT" \
    "${proactive_event_env[@]}" \
    "${external_mcp_env[@]}" \
    "SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true" \
    "SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000" \
    "?SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000" \
    "XHS_BACKEND_MCP_TIMEOUT_MS=90000" \
    "MEDIA_READER_MCP_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000" \
    "PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3" \
    "PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000" \
    "PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000" \
    "${media_reader_ocr_env[@]}" \
    "XHS_GENERIC_FALLBACK_READY_PATH=/opt/ran_agent/.ran_agent_state/social_reader/generic-fallback-ready.json" \
    "?XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0" \
    "WEIXIN_SDK_INBOUND_MEDIA_DIRS=$WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT" \
    "${xhs_public_env[@]}" \
    "${ombre_env[@]}"
}

filter_obsidian_memory_from_config() {
  local file="$1"
  local tmp_filter
  tmp_filter="$(mktemp)"
  awk '
    /^mcp_servers:/ { in_mcp=1 }
    in_mcp && /^  obsidian_memory:/ { skip=1; next }
    in_mcp && skip && /^  [^ ]/ { skip=0 }
    in_mcp && skip { next }
    /^platform_toolsets:/ { in_pt=1 }
    in_pt && /mcp-obsidian_memory/ { next }
    { print }
  ' "$file" >| "$tmp_filter"
  "${SUDO[@]}" cp "$tmp_filter" "$file"
  rm -f "$tmp_filter"
}

filter_ombre_memory_from_config() {
  local file="$1"
  local tmp_filter
  tmp_filter="$(mktemp)"
  awk '
    /^mcp_servers:/ { in_mcp=1 }
    in_mcp && /^  ombre_memory:/ { skip=1; next }
    in_mcp && /^  ombre_memory_extra:/ { skip=1; next }
    in_mcp && skip && /^  [^ ]/ { skip=0 }
    in_mcp && skip { next }
    /^platform_toolsets:/ { in_pt=1 }
    in_pt && /mcp-ombre_memory/ { next }
    in_pt && /mcp-ombre_memory_extra/ { next }
    { print }
  ' "$file" >| "$tmp_filter"
  "${SUDO[@]}" cp "$tmp_filter" "$file"
  rm -f "$tmp_filter"
}

write_lite_runtime_config() {
  log "refreshing lite runtime config"
  install_file_portable 644 "$REPO_ROOT/hermes/profile/config.lite.yaml" "$LITE_HOME/config.yaml"
  install_file_portable 644 "$REPO_ROOT/hermes/profile/config.lite.yaml" "$LITE_HOME/profiles/$LITE_PROFILE/config.yaml"
  filter_ombre_memory_from_config "$LITE_HOME/config.yaml"
  filter_ombre_memory_from_config "$LITE_HOME/profiles/$LITE_PROFILE/config.yaml"
  if [ "${OBSIDIAN_MEMORY_MCP_ENABLED:-false}" = "false" ]; then
    filter_obsidian_memory_from_config "$LITE_HOME/config.yaml"
    filter_obsidian_memory_from_config "$LITE_HOME/profiles/$LITE_PROFILE/config.yaml"
  fi
  chown_if_user_exists "$LITE_HOME"
}

write_full_runtime_config() {
  local profile_config="$FULL_HOME/profiles/$FULL_PROFILE/config.yaml"
  local runtime_config="$FULL_HOME/config.yaml"
  local tmp

  log "refreshing full runtime config"
  if ! "${SUDO[@]}" test -f "$profile_config"; then
    echo "ERROR: missing installed full profile config: $profile_config" >&2
    exit 1
  fi

  tmp="$(mktemp)"
  cat >| "$tmp" <<EOF
# Generated by scripts/apply-hermes-runtime-split.sh.
# Secrets stay in .env files; this file contains runtime shape only.

model:
  provider: deepseek
  default: $MODEL_NAME
  model: $MODEL_NAME
  base_url: https://api.deepseek.com/v1
  api_mode: chat_completions

web:
  search_backend: tavily
  extract_backend: tavily

compression:
  enabled: true
  threshold: 0.35
  target_ratio: 0.12
  protect_last_n: 8
  hygiene_hard_message_limit: 160

auxiliary:
  compression:
    provider: main
    model: ''
    base_url: null
  web_extract:
    provider: main
    model: ''
    base_url: null
  session_search:
    provider: main
    model: ''
    base_url: null

terminal:
  backend: local
  cwd: /opt/ran_agent
  timeout: 180
  lifetime_seconds: 300

disabled_tools:
  - browser_vision
  - image_generate
  - text_to_speech
  - video_analyze
  - vision_analyze
  - terminal
  - file
  - sticker_save_from_inbox
  - sticker_update
  - sticker_delete

platform_toolsets:
  cli:
    - web
    - skills
    - memory
    - session_search
    - safe
    - mcp-time
    - mcp-social_reader
    - mcp-media_reader
    - mcp-search_hub
    - mcp-co_reading
    - mcp-sticker_catalog
    - mcp-media_generation
    - mcp-personal_memory
    - mcp-obsidian_memory
    - mcp-ombre_memory
    - mcp-ombre_memory_extra
    - mcp-playwright
  gateway:
    - web
    - skills
    - memory
    - session_search
    - safe
    - mcp-time
    - mcp-social_reader
    - mcp-media_reader
    - mcp-search_hub
    - mcp-co_reading
    - mcp-sticker_catalog
    - mcp-media_generation
    - mcp-personal_memory
    - mcp-obsidian_memory
    - mcp-ombre_memory
    - mcp-ombre_memory_extra
    - mcp-playwright

EOF

  "${SUDO[@]}" awk 'BEGIN { copy=0 } /^mcp_servers:/ { copy=1 } copy { print }' "$profile_config" >> "$tmp"
  if ! "${SUDO[@]}" grep -Eq '^  tavily:' "$profile_config"; then
    cat >> "$tmp" <<'EOF'

  tavily:
    url: "https://mcp.tavily.com/mcp/?tavilyApiKey=${TAVILY_API_KEY}"
    timeout: 60
    connect_timeout: 30
EOF
  fi

  if [ "${OBSIDIAN_MEMORY_MCP_ENABLED:-false}" = "false" ]; then
    filter_obsidian_memory_from_config "$tmp"
  fi
  if ! ombre_mcp_should_be_exposed; then
    if ombre_brain_enabled && bool_is_true "$(effective_env_value OMBRE_BRAIN_MCP_ENABLED "$OMBRE_BRAIN_MCP_ENABLED_DEFAULT")"; then
      log "WARNING: Ombre Brain runner is not available; omitting direct Ombre MCP from full Hermes config"
    fi
    filter_ombre_memory_from_config "$tmp"
  fi

  install_file_portable 644 "$tmp" "$runtime_config"
  chown_if_user_exists "$runtime_config"
  rm -f "$tmp"
}

write_systemd_units() {
  log "refreshing systemd units"
  write_file 0644 "$LITE_SERVICE" <<EOF
[Unit]
Description=Ran Agent Hermes Lite Gateway (port $LITE_PORT)
After=network-online.target ran-agent-python.service
Wants=network-online.target

[Service]
Type=simple
User=$RUNTIME_USER
WorkingDirectory=/opt/ran_agent
EnvironmentFile=-$NODE_ENV_FILE
EnvironmentFile=-$NODE_BRIDGE_ENV_FILE
EnvironmentFile=-$HERMES_GLOBAL_ENV_FILE
EnvironmentFile=-$LITE_HOME/.env
EnvironmentFile=-$LITE_HOME/profiles/$LITE_PROFILE/.env
Environment=RAN_AGENT_REPO_ROOT=/opt/ran_agent
Environment=HERMES_HOME=$LITE_HOME
Environment=HERMES_PROFILE=$LITE_PROFILE
Environment=API_SERVER_ENABLED=true
Environment=API_SERVER_HOST=$API_HOST
Environment=API_SERVER_PORT=$LITE_PORT
Environment=API_SERVER_MODEL_NAME=$LITE_PROFILE
Environment=HERMES_API_BASE_URL=http://$API_HOST:$LITE_PORT/v1
Environment=HERMES_REPLY_MODE=api
Environment=HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT
Environment=HERMES_RESTART_DRAIN_TIMEOUT=60
Environment=PYTHON_BACKEND_BASE_URL=http://127.0.0.1:8787
Environment=PYTHON_BACKEND_INGEST_TIMEOUT_MS=5000
Environment=PERSONAL_MEMORY_BACKEND_TIMEOUT_MS=5000
Environment=PERSONAL_AGENT_PROACTIVE_ENABLED=false
Environment=PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED=false
Environment=HERMES_PROACTIVE_EVENTS_ENABLED=$HERMES_PROACTIVE_EVENTS_ENABLED_DEFAULT
Environment=HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED=$HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED_DEFAULT
Environment=HERMES_PROACTIVE_REMINDERS_ENABLED=$HERMES_PROACTIVE_REMINDERS_ENABLED_DEFAULT
Environment=UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache
Environment=UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools
Environment=UV_LINK_MODE=copy
Environment=UV_PYTHON_DOWNLOADS=never
Environment=SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true
Environment=SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000
Environment=SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000
Environment=XHS_BACKEND_MCP_TIMEOUT_MS=90000
Environment=XHS_PUBLIC_SIDECAR_ENABLED=$XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_URL=$XHS_PUBLIC_SIDECAR_URL_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_TIMEOUT_MS=$XHS_PUBLIC_SIDECAR_TIMEOUT_MS_DEFAULT
Environment=XHS_PUBLIC_HTML_FALLBACK_ENABLED=$XHS_PUBLIC_HTML_FALLBACK_ENABLED_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_MARKER_PATH=$XHS_PUBLIC_SIDECAR_MARKER_PATH_DEFAULT
Environment=MEDIA_READER_MCP_TIMEOUT_MS=1200000
Environment=PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000
Environment=PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3
Environment=PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000
Environment=PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000
Environment=PERSONAL_AGENT_OCR_PROVIDER=$PERSONAL_AGENT_OCR_PROVIDER_DEFAULT
Environment=PERSONAL_AGENT_OCR_MODEL=$PERSONAL_AGENT_OCR_MODEL_DEFAULT
Environment=PERSONAL_AGENT_OCR_TIMEOUT_MS=$PERSONAL_AGENT_OCR_TIMEOUT_MS_DEFAULT
Environment=XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0
Environment=OBSIDIAN_MEMORY_MCP_ENABLED=false
ExecStart=/usr/bin/env bash -lc 'cd /opt/ran_agent && source /opt/ran_agent/.venv/bin/activate && exec hermes -p $LITE_PROFILE gateway run --replace --accept-hooks'
Restart=always
RestartSec=5
TimeoutStopSec=240

[Install]
WantedBy=multi-user.target
EOF

  write_file 0644 "$FULL_SERVICE" <<EOF
[Unit]
Description=Ran Agent Hermes Full Gateway (port $FULL_PORT)
After=network-online.target ran-agent-python.service
Wants=network-online.target

[Service]
Type=simple
User=$RUNTIME_USER
WorkingDirectory=/opt/ran_agent
EnvironmentFile=-$NODE_ENV_FILE
EnvironmentFile=-$NODE_BRIDGE_ENV_FILE
EnvironmentFile=-$HERMES_GLOBAL_ENV_FILE
EnvironmentFile=-$FULL_HOME/.env
EnvironmentFile=-$FULL_HOME/profiles/$FULL_PROFILE/.env
Environment=RAN_AGENT_REPO_ROOT=/opt/ran_agent
Environment=HERMES_HOME=$FULL_HOME
Environment=HERMES_PROFILE=$FULL_PROFILE
Environment=API_SERVER_ENABLED=true
Environment=API_SERVER_HOST=$API_HOST
Environment=API_SERVER_PORT=$FULL_PORT
Environment=API_SERVER_MODEL_NAME=$FULL_PROFILE
Environment=HERMES_API_BASE_URL=http://$API_HOST:$FULL_PORT/v1
Environment=HERMES_REPLY_MODE=api
Environment=HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT
Environment=HERMES_RESTART_DRAIN_TIMEOUT=60
Environment=PYTHON_BACKEND_BASE_URL=http://127.0.0.1:8787
Environment=PYTHON_BACKEND_INGEST_TIMEOUT_MS=5000
Environment=PERSONAL_MEMORY_BACKEND_TIMEOUT_MS=5000
Environment=PERSONAL_AGENT_PROACTIVE_ENABLED=false
Environment=PERSONAL_AGENT_REMINDER_DELIVERY_ENABLED=false
Environment=HERMES_PROACTIVE_EVENTS_ENABLED=$HERMES_PROACTIVE_EVENTS_ENABLED_DEFAULT
Environment=HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED=$HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED_DEFAULT
Environment=HERMES_PROACTIVE_REMINDERS_ENABLED=$HERMES_PROACTIVE_REMINDERS_ENABLED_DEFAULT
Environment=UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache
Environment=UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools
Environment=UV_LINK_MODE=copy
Environment=UV_PYTHON_DOWNLOADS=never
Environment=SOCIAL_READER_GENERIC_FALLBACK_ENABLED=true
Environment=SOCIAL_READER_XHS_BACKEND_TIMEOUT_MS=90000
Environment=SOCIAL_READER_XHS_GENERIC_FALLBACK_TIMEOUT_MS=90000
Environment=XHS_BACKEND_MCP_TIMEOUT_MS=90000
Environment=XHS_PUBLIC_SIDECAR_ENABLED=$XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_URL=$XHS_PUBLIC_SIDECAR_URL_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_TIMEOUT_MS=$XHS_PUBLIC_SIDECAR_TIMEOUT_MS_DEFAULT
Environment=XHS_PUBLIC_HTML_FALLBACK_ENABLED=$XHS_PUBLIC_HTML_FALLBACK_ENABLED_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_MARKER_PATH=$XHS_PUBLIC_SIDECAR_MARKER_PATH_DEFAULT
Environment=MEDIA_READER_MCP_TIMEOUT_MS=1200000
Environment=PERSONAL_AGENT_MEDIA_DOWNLOAD_TIMEOUT_MS=60000
Environment=PERSONAL_AGENT_MEDIA_MAX_CONCURRENCY=3
Environment=PERSONAL_AGENT_MEDIA_BATCH_TIMEOUT_MS=1200000
Environment=PERSONAL_AGENT_MEDIA_PER_ITEM_TIMEOUT_MS=120000
Environment=PERSONAL_AGENT_OCR_PROVIDER=$PERSONAL_AGENT_OCR_PROVIDER_DEFAULT
Environment=PERSONAL_AGENT_OCR_MODEL=$PERSONAL_AGENT_OCR_MODEL_DEFAULT
Environment=PERSONAL_AGENT_OCR_TIMEOUT_MS=$PERSONAL_AGENT_OCR_TIMEOUT_MS_DEFAULT
Environment=XHS_GENERIC_FALLBACK_MIN_VERSION=1.2.0
Environment=OBSIDIAN_MEMORY_MCP_ENABLED=false
ExecStart=/usr/bin/env bash -lc 'cd /opt/ran_agent && source /opt/ran_agent/.venv/bin/activate && exec hermes -p $FULL_PROFILE gateway run --replace --accept-hooks'
Restart=always
RestartSec=5
TimeoutStopSec=240

[Install]
WantedBy=multi-user.target
EOF

  write_file 0644 "$OMBRE_SERVICE" <<EOF
[Unit]
Description=Ran Agent Ombre Brain Memory Service (port $OMBRE_BRAIN_PORT_DEFAULT)
After=network-online.target docker.service
Wants=network-online.target docker.service

[Service]
Type=simple
User=$RUNTIME_USER
WorkingDirectory=/opt/ran_agent
EnvironmentFile=-$NODE_ENV_FILE
EnvironmentFile=-$NODE_BRIDGE_ENV_FILE
EnvironmentFile=-$HERMES_GLOBAL_ENV_FILE
EnvironmentFile=-$FULL_HOME/.env
EnvironmentFile=-$FULL_HOME/profiles/$FULL_PROFILE/.env
Environment=RAN_AGENT_REPO_ROOT=/opt/ran_agent
ExecStart=/usr/bin/env bash -lc 'cd /opt/ran_agent && source /opt/ran_agent/.venv/bin/activate && exec bash scripts/start_ombre_brain_service.sh'
Restart=on-failure
RestartSec=10
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
EOF

  write_file 0644 "$XHS_PUBLIC_SIDECAR_SERVICE" <<EOF
[Unit]
Description=Ran Agent XHS Public Sidecar (XHS-Downloader API, port $XHS_PUBLIC_SIDECAR_PORT_DEFAULT)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUNTIME_USER
WorkingDirectory=/opt/ran_agent
EnvironmentFile=-$NODE_ENV_FILE
EnvironmentFile=-$NODE_BRIDGE_ENV_FILE
Environment=RAN_AGENT_REPO_ROOT=/opt/ran_agent
Environment=XHS_PUBLIC_SIDECAR_ENABLED=$XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_HOST=$XHS_PUBLIC_SIDECAR_HOST_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_PORT=$XHS_PUBLIC_SIDECAR_PORT_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_MARKER_PATH=$XHS_PUBLIC_SIDECAR_MARKER_PATH_DEFAULT
Environment=XHS_PUBLIC_SIDECAR_ROOT_DIR=$XHS_PUBLIC_SIDECAR_ROOT_DIR_DEFAULT
ExecStart=/usr/bin/env bash -lc 'cd /opt/ran_agent && source /opt/ran_agent/.venv/bin/activate && exec bash scripts/start_xhs_public_sidecar.sh'
Restart=on-failure
RestartSec=10
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
EOF

  # A release candidate deliberately does not repair legacy runtime drift:
  # those files may belong to an arbitrary installed MCP provider.
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ]; then
    cleanup_stale_lite_dropins
  fi
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ]; then
    "${SUDO[@]}" rm -f "$XHS_BROWSE_SERVICE"
  fi
}

cleanup_stale_lite_dropins() {
  local dropin
  for dropin in "${STALE_LITE_DROPINS[@]}"; do
    "${SUDO[@]}" rm -f "$dropin"
  done
}

systemd_unit_is_loaded() {
  local service="$1"
  local load_state
  load_state=$("${SUDO[@]}" systemctl show "$service" --property=LoadState --value 2>/dev/null) || return 1
  [ -n "$load_state" ] && [ "$load_state" != "not-found" ]
}

reset_failed_if_loaded() {
  local service
  for service in "$@"; do
    if systemd_unit_is_loaded "$service"; then
      "${SUDO[@]}" systemctl reset-failed "$service" >/dev/null 2>&1 || true
    fi
  done
}

xhs_public_sidecar_marker_ready() {
  local marker_path
  marker_path="$(effective_env_value XHS_PUBLIC_SIDECAR_MARKER_PATH "$XHS_PUBLIC_SIDECAR_MARKER_PATH_DEFAULT")"
  [ -f "$marker_path" ] || return 1
  python3 - "$marker_path" <<'PYEOF'
import json, os, sys
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        marker = json.load(fh)
except Exception:
    sys.exit(1)
required = [
    marker.get("source_dir", ""),
    marker.get("venv_python", ""),
]
ok = (
    marker.get("ok") is True
    and all(path and os.path.exists(path) for path in required)
    and os.access(marker.get("venv_python", ""), os.X_OK)
    and str(marker.get("api_url", "")).startswith("http://127.0.0.1:")
)
sys.exit(0 if ok else 1)
PYEOF
}

cleanup_account_backed_xhs_runtime() {
  log "removing account-backed XHS browse runtime surfaces"
  "${SUDO[@]}" systemctl disable --now ran-agent-xhs-browse.service >/dev/null 2>&1 || true
  "${SUDO[@]}" rm -f "$XHS_BROWSE_SERVICE"
  "${SUDO[@]}" rm -f \
    /opt/ran_agent/.ran_agent_state/social_reader/xhs-browse-ready.json \
    /opt/ran_agent/.ran_agent_state/social_reader/xhs-note-token-cache.json \
    /opt/ran_agent/node_bridge/.ran_agent_state/social_reader/xhs-note-token-cache.json
}

prepare_ombre_runtime() {
  if ! ombre_brain_enabled; then
    return 0
  fi
  log "preparing Ombre Brain runtime"
  if env \
    OMBRE_BRAIN_ENABLED="$(effective_env_value OMBRE_BRAIN_ENABLED "$OMBRE_BRAIN_ENABLED_DEFAULT")" \
    OMBRE_BRAIN_MCP_ENABLED="$(effective_env_value OMBRE_BRAIN_MCP_ENABLED "$OMBRE_BRAIN_MCP_ENABLED_DEFAULT")" \
    OMBRE_BRAIN_RUNNER="$(effective_env_value OMBRE_BRAIN_RUNNER "$OMBRE_BRAIN_RUNNER_DEFAULT")" \
    OMBRE_BRAIN_REPO_URL="$(effective_env_value OMBRE_BRAIN_REPO_URL "$OMBRE_BRAIN_REPO_URL_DEFAULT")" \
    OMBRE_BRAIN_HOME="$(effective_env_value OMBRE_BRAIN_HOME "$OMBRE_BRAIN_HOME_DEFAULT")" \
    OMBRE_BRAIN_SOURCE_DIR="$(effective_env_value OMBRE_BRAIN_SOURCE_DIR "$OMBRE_BRAIN_SOURCE_DIR_DEFAULT")" \
    OMBRE_BRAIN_VENV="$(effective_env_value OMBRE_BRAIN_VENV "$OMBRE_BRAIN_VENV_DEFAULT")" \
    OMBRE_BUCKETS_DIR="$(effective_env_value OMBRE_BUCKETS_DIR "$OMBRE_BUCKETS_DIR_DEFAULT")" \
    OMBRE_BRAIN_IMAGE="$(effective_env_value OMBRE_BRAIN_IMAGE "$OMBRE_BRAIN_IMAGE_DEFAULT")" \
    OMBRE_BRAIN_BIND_HOST="$(effective_env_value OMBRE_BRAIN_BIND_HOST "$OMBRE_BRAIN_BIND_HOST_DEFAULT")" \
    OMBRE_BRAIN_PORT="$(effective_env_value OMBRE_BRAIN_PORT "$OMBRE_BRAIN_PORT_DEFAULT")" \
    OMBRE_BRAIN_COMPOSE_FILE="$(effective_env_value OMBRE_BRAIN_COMPOSE_FILE "$OMBRE_BRAIN_COMPOSE_FILE_DEFAULT")" \
    OMBRE_BRAIN_CONFIG_FILE="$(effective_env_value OMBRE_BRAIN_CONFIG_FILE "$OMBRE_BRAIN_CONFIG_FILE_DEFAULT")" \
    OMBRE_BRAIN_STATUS_FILE="$(effective_env_value OMBRE_BRAIN_STATUS_FILE "$OMBRE_BRAIN_STATUS_FILE_DEFAULT")" \
    bash "$REPO_ROOT/scripts/prepare-ombre-brain.sh" 2>&1; then
    log "Ombre Brain runtime prepared"
  else
    log "WARNING: Ombre Brain preparation failed (non-blocking)"
  fi
}

restart_services() {
  log "reloading systemd and restarting services"
  "${SUDO[@]}" systemctl daemon-reload
  sleep 1
  if [ "$PRESERVE_RUNTIME_SHAPE" = "1" ]; then
    reset_failed_if_loaded ran-agent-python.service ran-agent-node.service ran-agent-hermes.service ran-agent-hermes-full.service
    "${SUDO[@]}" systemctl restart ran-agent-python.service
    "${SUDO[@]}" systemctl restart ran-agent-node.service
    "${SUDO[@]}" systemctl restart ran-agent-hermes.service
    "${SUDO[@]}" systemctl restart ran-agent-hermes-full.service
    return 0
  fi
  reset_failed_if_loaded ran-agent-python.service ran-agent-node.service ran-agent-hermes.service ran-agent-hermes-full.service ran-agent-ombre-brain.service ran-agent-xhs-public-sidecar.service
  cleanup_account_backed_xhs_runtime
  if ombre_brain_enabled; then
    if ombre_runner_available; then
      "${SUDO[@]}" systemctl enable ran-agent-ombre-brain.service >/dev/null 2>&1 || true
      if "${SUDO[@]}" systemctl restart ran-agent-ombre-brain.service; then
        log "Ombre Brain service restart requested"
      else
        log "WARNING: Ombre Brain service restart failed (non-blocking)"
      fi
    else
      log "WARNING: Ombre Brain runner is not available; service prepared but not started"
      "${SUDO[@]}" systemctl disable --now ran-agent-ombre-brain.service >/dev/null 2>&1 || true
    fi
  else
    "${SUDO[@]}" systemctl disable --now ran-agent-ombre-brain.service >/dev/null 2>&1 || true
  fi
  if bool_is_true "$XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT" && xhs_public_sidecar_marker_ready; then
    "${SUDO[@]}" systemctl enable ran-agent-xhs-public-sidecar.service >/dev/null 2>&1 || true
    if "${SUDO[@]}" systemctl restart ran-agent-xhs-public-sidecar.service; then
      log "XHS public sidecar service restart requested"
    else
      log "WARNING: XHS public sidecar service restart failed (non-blocking)"
    fi
  else
    log "XHS public sidecar marker not ready or disabled; service disabled until prepare succeeds"
    "${SUDO[@]}" systemctl disable --now ran-agent-xhs-public-sidecar.service >/dev/null 2>&1 || true
  fi
  "${SUDO[@]}" systemctl restart ran-agent-python.service
  "${SUDO[@]}" systemctl restart ran-agent-node.service
  "${SUDO[@]}" systemctl restart ran-agent-hermes.service
  wait_for_gateway_port "$LITE_PORT" ran-agent-hermes.service || true
  "${SUDO[@]}" systemctl restart ran-agent-hermes-full.service
  wait_for_gateway_port "$FULL_PORT" ran-agent-hermes-full.service || true
  "${SUDO[@]}" systemctl restart ran-agent-node.service
}

print_failure_context() {
  echo ""
  echo "ERROR: Hermes runtime split verification failed." >&2
  echo "--- effective systemd units (systemctl cat) ---" >&2
  "${SUDO[@]}" systemctl cat ran-agent-hermes.service ran-agent-hermes-full.service ran-agent-xhs-public-sidecar.service >&2 || true
  echo "--- service status ---" >&2
  "${SUDO[@]}" systemctl --no-pager --full status ran-agent-python.service ran-agent-hermes.service ran-agent-hermes-full.service ran-agent-xhs-public-sidecar.service ran-agent-node.service >&2 || true
  echo "--- recent Hermes logs ---" >&2
  "${SUDO[@]}" journalctl -u ran-agent-hermes.service -u ran-agent-hermes-full.service -u ran-agent-xhs-public-sidecar.service -n 120 --no-pager >&2 || true
  echo "--- listening sockets ---" >&2
  ss -ltnp >&2 || true
}

pid_has_env() {
  local pid="$1"
  local expected="$2"
  if [ "$EUID" -eq 0 ]; then
    tr '\0' '\n' < "/proc/$pid/environ" | grep -qx "$expected"
  else
    sudo sh -c "tr '\0' '\n' < '/proc/$pid/environ'" | grep -qx "$expected"
  fi
}

port_is_listening() {
  local port="$1"
  ss -ltnH | awk '{ print $4 }' | grep -Eq "(:|\\])$port$"
}

wait_for_gateway_port() {
  local port="$1"
  local service="$2"
  local waited=0
  while [ "$waited" -le 90 ]; do
    if port_is_listening "$port"; then
      return 0
    fi
    if ! "${SUDO[@]}" systemctl is-active --quiet "$service"; then
      return 1
    fi
    sleep 3
    waited=$((waited + 3))
  done
  return 1
}

systemd_cat_contains() {
  local service="$1"
  local pattern="$2"
  local output
  output=$("${SUDO[@]}" systemctl cat "$service" 2>/dev/null) || return 1
  printf '%s\n' "$output" | grep -qF "$pattern"
}

config_has_toolset() {
  local file="$1"
  local toolset="$2"
  awk '
    /^mcp_servers:/ { in_toolsets=0 }
    /^platform_toolsets:/ { in_toolsets=1 }
    in_toolsets { print }
  ' "$file" | grep -q -- "$toolset"
}

verify_runtime() {
  local lite_pid
  local full_pid

  log "verifying compact systemd units"
  # Cache systemctl cat output once for all checks
  local lite_cat full_cat
  lite_cat=$("${SUDO[@]}" systemctl cat ran-agent-hermes.service 2>/dev/null) || lite_cat=""
  full_cat=$("${SUDO[@]}" systemctl cat ran-agent-hermes-full.service 2>/dev/null) || full_cat=""

  systemd_cat_contains_cached() {
    local cat_output="$1"
    local pattern="$2"
    printf '%s\n' "$cat_output" | grep -qF "$pattern"
  }

  if ! systemd_cat_contains_cached "$lite_cat" 'Environment=HERMES_HOME=/home/ubuntu/.hermes-ran-agent/lite'; then
    echo "ERROR: lite systemd unit is not compacted to lite HERMES_HOME" >&2
    echo "--- systemctl cat ran-agent-hermes.service (first 30 lines) ---" >&2
    printf '%s\n' "$lite_cat" | head -30 >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$lite_cat" 'Environment=HERMES_PROFILE=ran-assistant-lite'; then
    echo "ERROR: lite systemd unit missing ran-assistant-lite profile" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$lite_cat" 'Environment=API_SERVER_PORT=8642'; then
    echo "ERROR: lite systemd unit missing API_SERVER_PORT=8642" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$lite_cat" 'Environment=API_SERVER_MODEL_NAME=ran-assistant-lite'; then
    echo "ERROR: lite systemd unit missing ran-assistant-lite model name" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$lite_cat" "Environment=HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT"; then
    echo "ERROR: lite systemd unit missing HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$lite_cat" 'hermes -p ran-assistant-lite gateway run'; then
    echo "ERROR: lite systemd unit ExecStart is not ran-assistant-lite gateway" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$full_cat" 'Environment=HERMES_HOME=/home/ubuntu/.hermes-ran-agent'; then
    echo "ERROR: full systemd unit missing full HERMES_HOME" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$full_cat" 'Environment=HERMES_PROFILE=ran-assistant'; then
    echo "ERROR: full systemd unit missing ran-assistant profile" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$full_cat" 'Environment=API_SERVER_PORT=8643'; then
    echo "ERROR: full systemd unit missing API_SERVER_PORT=8643" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$full_cat" 'Environment=API_SERVER_MODEL_NAME=ran-assistant'; then
    echo "ERROR: full systemd unit missing ran-assistant model name" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$full_cat" "Environment=HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT"; then
    echo "ERROR: full systemd unit missing HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT" >&2
    exit 1
  fi
  if ! systemd_cat_contains_cached "$full_cat" 'hermes -p ran-assistant gateway run'; then
    echo "ERROR: full systemd unit ExecStart is not ran-assistant gateway" >&2
    exit 1
  fi
  for uv_env in 'UV_CACHE_DIR=/opt/ran_agent/.ran_agent_state/uv-cache' 'UV_TOOL_DIR=/opt/ran_agent/.ran_agent_state/uv-tools' 'UV_LINK_MODE=copy' 'UV_PYTHON_DOWNLOADS=never'; do
    if ! systemd_cat_contains_cached "$lite_cat" "$uv_env"; then
      echo "ERROR: lite systemd unit missing $uv_env" >&2
      exit 1
    fi
    if ! systemd_cat_contains_cached "$full_cat" "$uv_env"; then
      echo "ERROR: full systemd unit missing $uv_env" >&2
      exit 1
    fi
  done
  while IFS= read -r media_dir; do
    if ! "${SUDO[@]}" test -d "$media_dir"; then
      echo "ERROR: missing runtime trusted media directory: $media_dir" >&2
      exit 1
    fi
  done < <(trusted_runtime_media_dirs)
  for node_env in \
    "HERMES_CONTEXT_INJECTION_MODE=$HERMES_CONTEXT_INJECTION_MODE_DEFAULT" \
    "HERMES_CONTEXT_CACHE_STRATEGY=$HERMES_CONTEXT_CACHE_STRATEGY_DEFAULT" \
    "HERMES_RECENT_TEXT_TURNS=$HERMES_RECENT_TEXT_TURNS_DEFAULT" \
    "HERMES_RECENT_TEXT_CHAR_BUDGET=$HERMES_RECENT_TEXT_CHAR_BUDGET_DEFAULT" \
    "HERMES_GLOBAL_RECENT_TURNS=$HERMES_GLOBAL_RECENT_TURNS_DEFAULT" \
    "HERMES_GLOBAL_RECENT_CHAR_BUDGET=$HERMES_GLOBAL_RECENT_CHAR_BUDGET_DEFAULT" \
    "HERMES_ACTIVE_TOPIC_CHAR_BUDGET=$HERMES_ACTIVE_TOPIC_CHAR_BUDGET_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY=$HERMES_CACHE_FRIENDLY_HISTORY_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS=$HERMES_CACHE_FRIENDLY_HISTORY_MAX_TURNS_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET=$HERMES_CACHE_FRIENDLY_HISTORY_CHAR_BUDGET_DEFAULT" \
    "HERMES_CACHE_FRIENDLY_HISTORY_PROFILE=$HERMES_CACHE_FRIENDLY_HISTORY_PROFILE_DEFAULT" \
    "HERMES_CACHE_TELEMETRY_ENABLED=$HERMES_CACHE_TELEMETRY_ENABLED_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_ENABLED=$HERMES_LITE_SOFT_RESET_ENABLED_DEFAULT" \
    "HERMES_LITE_SOFT_RESET_DRY_RUN=$HERMES_LITE_SOFT_RESET_DRY_RUN_DEFAULT" \
    "HERMES_ACTION_GATE_ENABLED=$HERMES_ACTION_GATE_ENABLED_DEFAULT" \
    "HERMES_ACTION_GATE_MODE=$HERMES_ACTION_GATE_MODE_DEFAULT" \
    "HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS=$HERMES_ACTION_GATE_MAX_REPAIR_ATTEMPTS_DEFAULT" \
    "HERMES_ACTION_PENDING_ENABLED=$HERMES_ACTION_PENDING_ENABLED_DEFAULT" \
    "HERMES_ACTION_PENDING_TTL_MINUTES=$HERMES_ACTION_PENDING_TTL_MINUTES_DEFAULT" \
    "HERMES_REPLY_TIMEOUT_SECONDS=$HERMES_REPLY_TIMEOUT_SECONDS_DEFAULT" \
    "NODE_BRIDGE_QUICK_ACK_ENABLED=$NODE_BRIDGE_QUICK_ACK_ENABLED_DEFAULT" \
    "NODE_BRIDGE_QUICK_ACK_TIMEOUT_MS=$NODE_BRIDGE_QUICK_ACK_TIMEOUT_MS_DEFAULT" \
    "NODE_BRIDGE_QUICK_ACK_TEXT=$NODE_BRIDGE_QUICK_ACK_TEXT_DEFAULT" \
    "FEISHU_SEND_TIMEOUT_SECONDS=$FEISHU_SEND_TIMEOUT_SECONDS_DEFAULT" \
    "FEISHU_DOWNLOAD_TIMEOUT_SECONDS=$FEISHU_DOWNLOAD_TIMEOUT_SECONDS_DEFAULT" \
    "HERMES_PROACTIVE_EVENTS_ENABLED=$HERMES_PROACTIVE_EVENTS_ENABLED_DEFAULT" \
    "HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED=$HERMES_PROACTIVE_EXTERNAL_MCP_ENABLED_DEFAULT" \
    "HERMES_PROACTIVE_REMINDERS_ENABLED=$HERMES_PROACTIVE_REMINDERS_ENABLED_DEFAULT" \
    "HERMES_PROACTIVE_NOTIFY_MAX_CHARS=$HERMES_PROACTIVE_NOTIFY_MAX_CHARS_DEFAULT" \
    "EXTERNAL_MCP_GATEWAY_ALLOW_ENV_ENABLE=$EXTERNAL_MCP_GATEWAY_ALLOW_ENV_ENABLE_DEFAULT" \
    "EXTERNAL_MCP_GATEWAY_ENABLED=$EXTERNAL_MCP_GATEWAY_ENABLED_DEFAULT" \
    "EXTERNAL_MCP_SYSTEM_QUEUE_ENABLED=$EXTERNAL_MCP_SYSTEM_QUEUE_ENABLED_DEFAULT" \
    "EXTERNAL_MCP_ACTIVITY_RUNNER_ENABLED=$EXTERNAL_MCP_ACTIVITY_RUNNER_ENABLED_DEFAULT" \
    "EXTERNAL_MCP_ACTIVITY_TICK_MS=$EXTERNAL_MCP_ACTIVITY_TICK_MS_DEFAULT" \
    "WEIXIN_SDK_INBOUND_MEDIA_DIRS=$WEIXIN_SDK_INBOUND_MEDIA_DIRS_DEFAULT" \
    "PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS=$PERSONAL_AGENT_QWEN_TIMEOUT_SECONDS_DEFAULT" \
    "PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS=$PERSONAL_AGENT_KNOWLEDGE_CRON_HOURS_DEFAULT" \
    "PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE=$PERSONAL_AGENT_KNOWLEDGE_CRON_MINUTE_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED=$PERSONAL_AGENT_DAILY_CARRYOVER_ENABLED_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_HOUR=$PERSONAL_AGENT_DAILY_CARRYOVER_HOUR_DEFAULT" \
    "PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE=$PERSONAL_AGENT_DAILY_CARRYOVER_MINUTE_DEFAULT" \
    "AI_DAILY_DIGEST_ENABLED=$AI_DAILY_DIGEST_ENABLED_DEFAULT" \
    "AI_DAILY_DIGEST_HOUR=$AI_DAILY_DIGEST_HOUR_DEFAULT" \
    "AI_DAILY_DIGEST_MINUTE=$AI_DAILY_DIGEST_MINUTE_DEFAULT"; do
    if ! "${SUDO[@]}" grep -q "^$node_env$" "$NODE_ENV_FILE"; then
      echo "ERROR: node env missing context optimization default $node_env" >&2
      exit 1
    fi
  done
  local stale_dropin
  for stale_dropin in "${STALE_LITE_DROPINS[@]}"; do
    if "${SUDO[@]}" test -e "$stale_dropin"; then
      echo "ERROR: stale Hermes runtime drop-in remains: $stale_dropin" >&2
      exit 1
    fi
  done

  log "verifying gateway processes and ports"
  sleep 2
  lite_pid="$(pgrep -u "$RUNTIME_USER" -f "hermes -p $LITE_PROFILE gateway run" | head -n 1 || true)"
  full_pid="$(pgrep -u "$RUNTIME_USER" -f "hermes -p $FULL_PROFILE gateway run" | head -n 1 || true)"

  if [ -z "$lite_pid" ] || [ -z "$full_pid" ]; then
    print_failure_context
    exit 1
  fi
  if ! pid_has_env "$lite_pid" "API_SERVER_PORT=$LITE_PORT"; then
    print_failure_context
    exit 1
  fi
  if ! pid_has_env "$full_pid" "API_SERVER_PORT=$FULL_PORT"; then
    print_failure_context
    exit 1
  fi
  wait_for_gateway_port "$LITE_PORT" ran-agent-hermes.service || true
  wait_for_gateway_port "$FULL_PORT" ran-agent-hermes-full.service || true
  if ! port_is_listening "$LITE_PORT" || ! port_is_listening "$FULL_PORT"; then
    print_failure_context
    exit 1
  fi

  log "verifying Search Hub source and runtime config"
  if ! grep -q '"search_hub"' "$REPO_ROOT/.mcp.json"; then
    echo "ERROR: .mcp.json does not register search_hub" >&2
    exit 1
  fi
  if ! grep -q '"sticker_catalog"' "$REPO_ROOT/.mcp.json"; then
    echo "ERROR: .mcp.json does not register sticker_catalog" >&2
    exit 1
  fi
  if ! grep -q '"ombre_memory"' "$REPO_ROOT/.mcp.json"; then
    echo "ERROR: .mcp.json does not register ombre_memory" >&2
    exit 1
  fi
  if ! grep -q 'mcp-search_hub' "$REPO_ROOT/hermes/profile/config.yaml"; then
    echo "ERROR: full source profile missing mcp-search_hub" >&2
    exit 1
  fi
  if ! grep -q 'mcp-ombre_memory' "$REPO_ROOT/hermes/profile/config.yaml"; then
    echo "ERROR: full source profile missing mcp-ombre_memory" >&2
    exit 1
  fi
  if ! grep -q 'mcp-sticker_catalog' "$REPO_ROOT/hermes/profile/config.yaml"; then
    echo "ERROR: full source profile missing mcp-sticker_catalog" >&2
    exit 1
  fi
  if ! grep -q 'mcp-search_hub' "$REPO_ROOT/hermes/profile/config.lite.yaml"; then
    echo "ERROR: lite source profile missing mcp-search_hub" >&2
    exit 1
  fi
  if ! grep -q 'mcp-sticker_catalog' "$REPO_ROOT/hermes/profile/config.lite.yaml"; then
    echo "ERROR: lite source profile missing mcp-sticker_catalog" >&2
    exit 1
  fi
  if ! grep -q '^  search_hub:' "$FULL_HOME/config.yaml"; then
    echo "ERROR: full runtime config missing search_hub MCP server" >&2
    exit 1
  fi
  if ! grep -q '^  search_hub:' "$LITE_HOME/config.yaml"; then
    echo "ERROR: lite runtime config missing search_hub MCP server" >&2
    exit 1
  fi
  if ! grep -q '^  sticker_catalog:' "$FULL_HOME/config.yaml"; then
    echo "ERROR: full runtime config missing sticker_catalog MCP server" >&2
    exit 1
  fi
  if ! grep -q '^  sticker_catalog:' "$LITE_HOME/config.yaml"; then
    echo "ERROR: lite runtime config missing sticker_catalog MCP server" >&2
    exit 1
  fi
  if ! config_has_toolset "$LITE_HOME/config.yaml" 'mcp-search_hub'; then
    echo "ERROR: lite runtime toolset missing mcp-search_hub" >&2
    exit 1
  fi
  if ! config_has_toolset "$LITE_HOME/config.yaml" 'mcp-sticker_catalog'; then
    echo "ERROR: lite runtime toolset missing mcp-sticker_catalog" >&2
    exit 1
  fi
  if config_has_toolset "$LITE_HOME/config.yaml" 'mcp-playwright'; then
    echo "ERROR: lite runtime toolset exposes mcp-playwright" >&2
    exit 1
  fi
  if config_has_toolset "$LITE_HOME/config.yaml" 'mcp-media_generation'; then
    echo "ERROR: lite runtime toolset exposes mcp-media_generation" >&2
    exit 1
  fi
  if config_has_toolset "$LITE_HOME/config.yaml" 'mcp-ombre_memory'; then
    echo "ERROR: lite runtime toolset exposes mcp-ombre_memory" >&2
    exit 1
  fi
  if ! config_has_toolset "$FULL_HOME/config.yaml" 'mcp-search_hub'; then
    echo "ERROR: full runtime toolset missing mcp-search_hub" >&2
    exit 1
  fi
  if ! config_has_toolset "$FULL_HOME/config.yaml" 'mcp-sticker_catalog'; then
    echo "ERROR: full runtime toolset missing mcp-sticker_catalog" >&2
    exit 1
  fi
  if ! config_has_toolset "$FULL_HOME/config.yaml" 'mcp-playwright'; then
    echo "ERROR: full runtime toolset missing mcp-playwright" >&2
    exit 1
  fi
  if ! test -x "$REPO_ROOT/scripts/start_search_hub_mcp.sh"; then
    echo "ERROR: scripts/start_search_hub_mcp.sh missing or not executable" >&2
    exit 1
  fi
  if ! test -x "$REPO_ROOT/scripts/start_sticker_catalog_mcp.sh"; then
    echo "ERROR: scripts/start_sticker_catalog_mcp.sh missing or not executable" >&2
    exit 1
  fi
  if ombre_mcp_should_be_exposed; then
    if ! config_has_toolset "$FULL_HOME/config.yaml" 'mcp-ombre_memory'; then
      echo "ERROR: full runtime toolset missing mcp-ombre_memory while OMBRE_BRAIN_MCP_ENABLED=true" >&2
      exit 1
    fi
    if ! grep -q '^  ombre_memory:' "$FULL_HOME/config.yaml"; then
      echo "ERROR: full runtime config missing ombre_memory MCP server while OMBRE_BRAIN_MCP_ENABLED=true" >&2
      exit 1
    fi
  else
    if config_has_toolset "$FULL_HOME/config.yaml" 'mcp-ombre_memory'; then
      echo "ERROR: full runtime toolset exposes mcp-ombre_memory while Ombre runner is unavailable" >&2
      exit 1
    fi
    if grep -q '^  ombre_memory:' "$FULL_HOME/config.yaml"; then
      echo "ERROR: full runtime config exposes ombre_memory while Ombre runner is unavailable" >&2
      exit 1
    fi
  fi

  log "verifying obsidian_memory MCP config"
  if [ "${OBSIDIAN_MEMORY_MCP_ENABLED:-false}" = "false" ]; then
    if config_has_toolset "$LITE_HOME/config.yaml" 'mcp-obsidian_memory'; then
      echo "ERROR: lite runtime toolset exposes mcp-obsidian_memory but OBSIDIAN_MEMORY_MCP_ENABLED=false" >&2
      exit 1
    fi
    if config_has_toolset "$FULL_HOME/config.yaml" 'mcp-obsidian_memory'; then
      echo "ERROR: full runtime toolset exposes mcp-obsidian_memory but OBSIDIAN_MEMORY_MCP_ENABLED=false" >&2
      exit 1
    fi
    if grep -q '^  obsidian_memory:' "$LITE_HOME/config.yaml"; then
      echo "ERROR: lite runtime config has mcp_servers.obsidian_memory but OBSIDIAN_MEMORY_MCP_ENABLED=false" >&2
      exit 1
    fi
    if grep -q '^  obsidian_memory:' "$FULL_HOME/config.yaml"; then
      echo "ERROR: full runtime config has mcp_servers.obsidian_memory but OBSIDIAN_MEMORY_MCP_ENABLED=false" >&2
      exit 1
    fi
  fi

  if systemd_unit_is_loaded ran-agent-xhs-browse.service; then
    echo "ERROR: account-backed ran-agent-xhs-browse.service is still loaded" >&2
    exit 1
  fi
  if "${SUDO[@]}" test -e /opt/ran_agent/.ran_agent_state/social_reader/xhs-browse-ready.json; then
    echo "ERROR: account-backed XHS browse marker still exists" >&2
    exit 1
  fi
  if "${SUDO[@]}" test -e /opt/ran_agent/.ran_agent_state/social_reader/xhs-note-token-cache.json; then
    echo "ERROR: legacy XHS token cache still exists" >&2
    exit 1
  fi
  for env_file in "$NODE_ENV_FILE" "$NODE_BRIDGE_ENV_FILE" "$FULL_HOME/.env" "$LITE_HOME/.env" "$FULL_HOME/profiles/$FULL_PROFILE/.env" "$LITE_HOME/profiles/$LITE_PROFILE/.env"; do
    if "${SUDO[@]}" test -f "$env_file" && "${SUDO[@]}" grep -Eq '^(XHS_COOKIE|XHS_MCP_|PERSONAL_AGENT_XHS_MCP_|XHS_BROWSE_|SOCIAL_READER_EXPOSE_XHS_BROWSE_TOOLS|XHS_NOTE_TOKEN_CACHE_)' "$env_file"; then
      echo "ERROR: account-backed XHS env key remains in $env_file" >&2
      exit 1
    fi
  done

  if bool_is_true "$XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT" && xhs_public_sidecar_marker_ready; then
    if "${SUDO[@]}" systemctl is-active --quiet ran-agent-xhs-public-sidecar.service; then
      log "OK: XHS public sidecar service active"
    else
      log "WARNING: XHS public sidecar marker is ready, but ran-agent-xhs-public-sidecar.service is not active"
    fi
  else
    log "XHS public sidecar marker not ready; XHS remains public-only through wanyi/html fallbacks"
  fi

  log "OK: $LITE_PROFILE pid=$lite_pid port=$LITE_PORT"
  log "OK: $FULL_PROFILE pid=$full_pid port=$FULL_PORT"
}

main() {
  case "${1:-}" in
    '') ;;
    --preserve-runtime-shape) PRESERVE_RUNTIME_SHAPE=1 ;;
    *) echo "ERROR: invalid runtime split mode" >&2; exit 1 ;;
  esac

  # Candidate release mode changes code only.  Existing profile membership,
  # opaque MCP config, env files, and units stay owned by the operator.
  if [ "$PRESERVE_RUNTIME_SHAPE" = "1" ]; then
    require_command systemctl
    restart_services
    return 0
  fi

  # Drift repair installs profiles and generates units which directly invoke
  # Hermes.  Candidate release mode above only restarts existing units.
  require_command "$HERMES_BIN"
  require_command systemctl
  require_command journalctl
  require_command pgrep
  require_command ss
  require_command openssl

  ensure_runtime_dirs

  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ]; then
    backup_env_file full_home_env "$FULL_HOME/.env"
    backup_env_file full_profile_env "$FULL_HOME/profiles/$FULL_PROFILE/.env"
    backup_env_file lite_home_env "$LITE_HOME/.env"
    backup_env_file lite_profile_env "$LITE_HOME/profiles/$LITE_PROFILE/.env"
    backup_env_file node_env "$NODE_ENV_FILE"
    backup_env_file node_bridge_env "$NODE_BRIDGE_ENV_FILE"

    install_profiles

    restore_env_file full_home_env "$FULL_HOME/.env"
    restore_env_file full_profile_env "$FULL_HOME/profiles/$FULL_PROFILE/.env"
    restore_env_file lite_home_env "$LITE_HOME/.env"
    restore_env_file lite_profile_env "$LITE_HOME/profiles/$LITE_PROFILE/.env"
    restore_env_file node_env "$NODE_ENV_FILE"
    restore_env_file node_bridge_env "$NODE_BRIDGE_ENV_FILE"

    write_lite_runtime_config
  fi
  write_runtime_env
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ]; then
    prepare_ombre_runtime
    write_full_runtime_config
  fi
  write_systemd_units
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ]; then
    cleanup_account_backed_xhs_runtime
  fi

  # Prepare XHS generic fallback tool (non-blocking, before restart)
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ] && [ "${SOCIAL_READER_GENERIC_FALLBACK_ENABLED:-true}" != "false" ]; then
    log "preparing XHS generic fallback tool"
    if timeout "$XHS_GENERIC_FALLBACK_PREPARE_TIMEOUT_SECONDS" bash "$REPO_ROOT/scripts/prepare-xhs-generic-fallback.sh" 2>&1; then
      log "XHS generic fallback prepared"
    else
      log "WARNING: XHS generic fallback preparation failed or timed out (non-blocking)"
    fi
  fi

  # Prepare public XHS sidecar (non-blocking; it never receives cookies).
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ] && [ "$XHS_PUBLIC_SIDECAR_AUTO_PREPARE" != "false" ] && bool_is_true "$XHS_PUBLIC_SIDECAR_ENABLED_DEFAULT"; then
    log "preparing XHS public sidecar"
    if timeout "$XHS_PUBLIC_SIDECAR_PREPARE_TIMEOUT_SECONDS" bash "$REPO_ROOT/scripts/prepare-xhs-public-sidecar.sh" 2>&1; then
      log "XHS public sidecar prepared"
    else
      log "WARNING: XHS public sidecar preparation failed or timed out (non-blocking)"
    fi
  else
    log "XHS public sidecar auto-prepare disabled"
  fi

  restart_services
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ]; then
    verify_runtime
  fi
  if [ "$PRESERVE_RUNTIME_SHAPE" != "1" ] && [ -x "$REPO_ROOT/scripts/diagnose-media-xhs.sh" ]; then
    bash "$REPO_ROOT/scripts/diagnose-media-xhs.sh" --smoke-generic --smoke-public-sidecar --smoke-social-tools
  fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
